### ISSUE TITLE
No arrows ?

### ISSUE THREAD

**Issue by perfaram** [oh-my-fish/theme-bobthefish#1]
Hi !
In the screenshot that is provided, the prompt segments look like arrows. It's nice ! 
But, it just doesn't work with my setup... What's wrong ?
I'm on Yosemite (but I doubt it's relevant)
iTerm2 settings : Meslo Powerline 12points, Solarized Dark.
Any idea ?

**Comment by perfaram** [comment]
My bad... In iTerm2, there's two font selectors : one for standard ASCII text, another for non-ASCII. I had Menlo for the non-ASCII, but I should have had a Powerline-compatible font, like Meslo.

**Comment by bobthecow** [comment]
Yep! iTerm settings for fonts are a little confusing, unfortunately.
