### ISSUE TITLE
Unexpected line wrap happens in git directory.

### ISSUE THREAD

**Issue by amosbird** [oh-my-fish/theme-bobthefish#10]
![2015-10-12_154338](https://cloud.githubusercontent.com/assets/5085485/10423326/149f3d8c-70f8-11e5-94b5-682d8f650aca.png)

After the git repo becomes dirty, the right most `5` gets wrapped to the next line.

**Comment by bobthecow** [comment]
Assuming you're using iTerm, try changing this?

<img width="392" alt="screen shot 2015-10-12 at 8 01 35 am" src="https://cloud.githubusercontent.com/assets/53660/10431036/82256f98-70b7-11e5-8825-2fd2fc263132.png">

**Comment by amosbird** [comment]
I'm using `XShell` on Windows 10.
![v3u 8xzqk t c k v 093](https://cloud.githubusercontent.com/assets/5085485/10443744/dcb1a8f8-7190-11e5-99e6-e13b4bf05862.png)
still no good.

**Comment by bobthecow** [comment]
Yeah, I'm not sure. It's definitely not a CJK character. It could be that XShell is more aggressive about their wide characters than iTerm, and only let you disable it for CJK characters?

It looks like the issue is with the `…` character, not the branch glyph, right? Have you noticed it with any of the other symbols? I could add an alt style that uses something else for "untracked files", if that's the only one affected.

**Comment by amosbird** [comment]
@bobthecow Currently, no. I would love to test it if this alt style gets implemented.

**Comment by bobthecow** [comment]
@amosbird I've added a fix (though probably not the best fix). You can try it out by updating to the latest version of bobthefish, then adding this to your `.config/fish/config.fish` or `.config/omf/init.fish`:

```fish
set -g theme_avoid_ambiguous_glyphs yes
```

**Comment by amosbird** [comment]
Now the line wrap works correctly. But I keep getting this output.

![6p 3c w8a s2m kv4g_ m t](https://cloud.githubusercontent.com/assets/5085485/10477448/c1958488-7288-11e5-8dda-7a5decb90ab0.png)

**Comment by bobthecow** [comment]
Oh, boo. Those are a pain to track down.

My first guess is line 325. Do you mind checking it? Change this:

```fish
if [ (command git ls-files --other --exclude-standard) ]
```

To this:

```fish
set new (command git ls-files --other --exclude-standard)
if [ "$new" ]
```

**Comment by amosbird** [comment]
@bobthecow Thanks. Now it works properly.
