### ISSUE TITLE
Paths abbreviated regardless of setting

### ISSUE THREAD

**Issue by wizonesolutions** [oh-my-fish/theme-bobthefish#100]
I ran `set -g theme_title_use_abbreviated_path no`, but still seeing e.g. `~/v/m/acquia` as my path. Did I do something wrong? Do I have to kill fish for it to reload the config?

**Comment by bobthecow** [comment]
that setting only changes the path abbreviation for your terminal tab title. if you're trying to change it in the prompt itself, you need to set `fish_prompt_pwd_dir_length`:

> bobthefish respects the Fish `$fish_prompt_pwd_dir_length` setting to abbreviate the prompt path. Set to `0` to show the full path, `1` (default) to show only the first character of each parent directory name, or any other number to show up to that many characters.

**Comment by wizonesolutions** [comment]
Much appreciated.
