### ISSUE TITLE
math: Invalid expression error probably from cmd duration in right prompt

### ISSUE THREAD

**Issue by yogan** [oh-my-fish/theme-bobthefish#105]
I recently started using this theme and noticed that every now and then and get an error like this after a command execution:
```math: Invalid expression: Unexpected token ";36479/1000 " found at position 7.```
I assume that this is coming from the code that takes care of the duration shown in the right prompt. It seems to happen for longer running commands (e.g. an editor) - but not every time. However, when it occurs, I also often see a random character instead of the expected `1234ms`.

I don't have any fancy configuration. My fish is built from git (`72244dee`), omf is up-to-date, and the theme was installed with `omf install`. I know the error description is pretty vague, but I'll gladly help debugging this; I would need a hint on where to add some debugging lines however.

**Comment by bobthecow** [comment]
That is weird. 

For the error you pasted, that's https://github.com/oh-my-fish/theme-bobthefish/blob/master/fish_right_prompt.fish#L11 The first thing to test would be whether sleeping for 36 seconds triggers this again :)

```
sleep 36
```

Next, try doing the math yourself:

```
math "scale=1;36479/1000"
```

… all of which works great for me.

But even when I create a syntax error on purpose, I can't get the exact message you're getting. I wonder if it's a difference in the underlying `bc` version. What's your OS (and version), and what does `which -a bc` say?

**Comment by yogan** [comment]
The `sleep 36` seems to be able to reproduce the error. And for some reason the leading "scale=1" part is missing, as it will print:
```math: Invalid expression: Unexpected token ";36001/1000 " found at position 7.```
Calling that with `math ";36001/1000"` behaves the same.

My `bc` (`which bc` → `/usr/bin/bc`) is version 1.06.95-9 from Debian/jessie.

**Comment by yogan** [comment]
It just found this explanation in the issue tracker for fish-shell:
https://github.com/fish-shell/fish-shell/issues/4373#issuecomment-326746549
Does this help you to fix it?

**Comment by krader1961** [comment]
You've assumed `math` is a thin wrapper around `bc`. And while that is true in fish 1.x and 2.x it is not true for fish 3.0. You should switch to `math -s1 expr` or do `echo "scale=1; expr" | bc`.

**Comment by bobthecow** [comment]
I assumed that based on the first line of the man page:

>math is used to perform mathematical calculations. It is a very thin wrapper for the bc program, which makes it possible to specify an expression from the command line without using non-standard extensions or a pipeline.

And since I needed something where I could specify an expression from the command line without using non-standard extensions or a pipeline, it seemed like a good fit. You could understand how I might make the mistake of assuming it was a very thin wrapper for around `bc`, right?

:)

**Comment by bobthecow** [comment]
@yogan This should be fixed now. Mind giving it a shot?

@krader1961 Thanks for the help tracking it down.

**Comment by yogan** [comment]
@bobthecow It seems to work perfectly fine now. Thanks for the quick fix!

**Comment by bobthecow** [comment]
Great! Thanks for reporting the issue.
