### ISSUE TITLE
Working directory is displayed twice in git directories

### ISSUE THREAD

**Issue by letheed** [oh-my-fish/theme-bobthefish#106]
My prompt is looking like this in git directories:

`~/s/l/C/godot > master > /home/user/src/lang/C++/godot`

instead of 

`~/s/l/C/godot > master`

Not sure if I misconfigured something or if it's a bug.

**Comment by bobthecow** [comment]
Do you use git worktree?

**Comment by letheed** [comment]
Well I don't but apparently godot does. Thank you, I had no idea why that was happening.

**Comment by bobthecow** [comment]
No problem!
