### ISSUE TITLE
theme_title_use_abbreviated_path not working

### ISSUE THREAD

**Issue by claygorman** [oh-my-fish/theme-bobthefish#109]
It seems like theme_title_use_abbreviated_path doesnt do that it says. I still have ~/path and ~/u/path wether i set it to yes or no.

I was wondering if you are able to reproduce this?

**Comment by bobthecow** [comment]
To be clear, this is supposed to change the path in the tab title of your terminal app, not inside the shell itself. Is that not what you're seeing?

**Comment by claygorman** [comment]
I have attached a screenshot that hopefully clarifies what I am seeing. Thank you for your attention to this!

![screen shot 2017-10-13 at 1 31 46 pm](https://user-images.githubusercontent.com/4524500/31565257-f9757170-b01a-11e7-818e-b82167f93897.png)

**Comment by bobthecow** [comment]
Right. These are the title:

<img width="658" alt="screen_shot_2017-10-13_at_9_04_21_pm" src="https://user-images.githubusercontent.com/53660/31572433-b02f2930-b05a-11e7-945a-333ce6b29fb9.png">

… and they're controlled by `theme_title_use_abbreviated_path`. 

If you want to mess with abbreviation in the actual prompt, use the Fish-standard configuration variable `fish_prompt_pwd_dir_length`. Set it to `0` to disable truncation completely, or any other number to use up to that number of characters from each parent directory.

bobthefish also supports `theme_project_dir_length`, which can also be set to `0` or `1` or whatever control abbreviation of the path relative to the current git repo.

**Comment by claygorman** [comment]
ahh thank you for that. I am new to fish and wasnt aware. I appreciate your guidance!

**Comment by bobthecow** [comment]
Yep, no problem!
