### ISSUE TITLE
Fonts colour for changing command

### ISSUE THREAD

**Issue by ridicule777** [oh-my-fish/theme-bobthefish#110]
Hi! 

Could somebody please tell me who can i get the font colour while typing the commands to be dark-blue and blue as shown in the ReadMe file. Currently it is white and cyan for me. 
<img width="723" alt="terminal-font" src="https://user-images.githubusercontent.com/5362247/31579972-4e89aaf0-b160-11e7-920f-03508d4c7a2b.png">

**Comment by bobthecow** [comment]
Dark blue/blue used to be the default colors for commands and parameters (when the readme screencast was recorded) but it's white/cyan now. If you want the old default, run `fish_config` and select the "fish default" color palette. Or you can customize them to whatever you want :)

**Comment by ridicule777** [comment]
Thank you very much @bobthecow
I have a wonderful terminal now!! :)

**Comment by bobthecow** [comment]
No problem!
