### ISSUE TITLE
Feature Req: Please add ssh information

### ISSUE THREAD

**Issue by jschank** [oh-my-fish/theme-bobthefish#113]
Please allow indication of ssh status.

**Comment by bobthecow** [comment]
It should include hostname (and user) when using ssh. Are you not seeing this?

**Comment by jschank** [comment]
I believe it does. I suppose i was thinking of something more dramatic.
Sorry, i know that sounds vague. But i didnt realize the hostname wasnt the normal one.
I guess i was thinking of an indicator like when using vagrant. Or maybe a different color or icon, or something.

Thanks for responding.
Schank

**Comment by bobthecow** [comment]
This might be better now, with some of the username / hostname changes. Please update and see if that helps!

**Comment by jschank** [comment]
Thanks for thinking of me.
I’ll check it out.
