### ISSUE TITLE
fish_vi_key_bindings replace segment not shown

### ISSUE THREAD

**Issue by codemonkey800** [oh-my-fish/theme-bobthefish#120]
The `replace-one` mode has been renamed to `replace_one` in commit https://github.com/fish-shell/fish-shell/commit/a9db99ac52060a089c012bfea8e2036d18827d24.

The line to fix is here: https://github.com/oh-my-fish/theme-bobthefish/blob/69c737f592409d7b1a63b9dfd2770d981665d2ac/fish_prompt.fish#L396

**Comment by bobthecow** [comment]
Thanks! This is fixed by d657042.
