### ISSUE TITLE
Whitespace after Hostname is missing

### ISSUE THREAD

**Issue by derphilipp** [oh-my-fish/theme-bobthefish#121]
If the hostname is displayed, but the username is not, the prompt misses a whitespace after the hostname:
`> HOSTNAME> ~`

instead of

`> HOSTNAME > ~`

If displaying a username and the hostname, the problem does not occur.

Example:
![screen shot 2018-01-02 at 09 56 20](https://user-images.githubusercontent.com/429154/34478804-3ebac74a-efa3-11e7-9110-6db0a381b758.png) ❌ 

![screen shot 2018-01-02 at 09 55 55](https://user-images.githubusercontent.com/429154/34478803-3ea25782-efa3-11e7-80d4-932f35a2ab96.png) ✅

**Comment by bobthecow** [comment]
Thanks for reporting. This should be fixed now!

**Comment by derphilipp** [comment]
Perfect!
