### ISSUE TITLE
Strange empty section in the prompt

### ISSUE THREAD

**Issue by inflation** [oh-my-fish/theme-bobthefish#122]
Hi, I just updated the theme and it gives me this strange green section of an empty string at the left of the directory section:
![image](https://user-images.githubusercontent.com/2375962/34569138-cb407d3a-f1a2-11e7-8df5-e7b69aecde38.png)

I've tried to disable the display of everything set to 'yes' in default but no help. What could trigger this? Thank you.

**Comment by bobthecow** [comment]
From the color, that looks like it's the Kubernetes segment. If so, setting `theme_display_k8s_context` to `no` will disable it.

I'm curious, though, how it came to be an empty string, so if you can help track that down, it'd be super helpful :)

1. Do you use Kubernetes?
2. What's the value of `$KUBECONFIG` in your shell?
3. Is there a file at `~/.kube/config`, and what does it contain?

Thanks!

**Comment by inflation** [comment]
Oh yeah, I tried Kubernetes with GCP long way ago to explore it and forgot about it. There are some auto-configured data from `gcloud` and `$KUBECONFIG` is empty.

**Comment by inflation** [comment]
These are all expired and I suspect that `current-context: ''` cause it?
![image](https://user-images.githubusercontent.com/2375962/34596601-140bcf0a-f21c-11e7-91cf-49fee165a358.png)

**Comment by bobthecow** [comment]
Yep. That's our culprit!

**Comment by bobthecow** [comment]
This should be fixed now. Thanks for reporting it!
