### ISSUE TITLE
After update strange prompt section appeared

### ISSUE THREAD

**Issue by slavus** [oh-my-fish/theme-bobthefish#123]
After update to latest bobthefish strange prompt section appeared. I don't know how to disable it or what it means. As shown on the picture
![image](https://user-images.githubusercontent.com/992825/34598859-76d94400-f1ef-11e7-8733-6bea5ea543be.png)
In prompt bold part is unknown: 

N  **staza/192-168-99-100:8443/dev1**  user  ~     
Tihis prompt part: 
 staza/192-168-99-100:8443/dev1 
staza is name of supplication I am developing, and this is IP and port of this application  192-168-99-100:8443 but i don't know from what is this coming from, because it is not IP address from any local network adapter. 

What doest this prompt section mean, and how can I disable it ?

**Comment by bobthecow** [comment]
That segment is your current kubernetes context. To disable it, set `theme_display_k8s_context` to `no`.

**Comment by slavus** [comment]
Thanx,
That is it.
