### ISSUE TITLE
Bobthefish installation failed

### ISSUE THREAD

**Issue by naskz** [oh-my-fish/theme-bobthefish#124]
I've previously installed fish (2.2), currently on a Linux mint 18.3, decided to install omf + bobthefish but it doesn't works.
All others themes I tried are working but not that one.

⋊> ~/Downloads omf theme bobthefish                                     07:10:15
Theme not installed!
Install it using omf install bobthefish
⋊> ~/Downloads omf install bobthefish                                   07:10:21
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package bobthefish
✔ bobthefish successfully installed.
No command 'string' found, did you mean:
 Command 'strings' from package 'binutils-multiarch' (main)
 Command 'strings' from package 'binutils' (main)
 Command 'spring' from package 'ruby-spring' (universe)
 Command 'spring' from package 'spring' (universe)
string: command not found
~/.config/fish/functions/fish_prompt.fish (line 1): string replace -r '/[^/]+/?$' '' -- $argv
                                                    ^
in function “__bobthefish_dirname”
        called on line 76 of file ~/.config/fish/functions/fish_prompt.fish
        with parameter list “/home/nask/Downloads”

in command substitution
        called on line 74 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
        called on line 74 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_pretty_parent”
        called on line 273 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
        called on line 271 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_path_segment”
        called on line 814 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_prompt_dir”
        called on line 1557 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
        called on standard input

in command substitution
        called on standard input

No command 'string' found, did you mean:
 Command 'spring' from package 'spring' (universe)
 Command 'spring' from package 'ruby-spring' (universe)
 Command 'strings' from package 'binutils' (main)
 Command 'strings' from package 'binutils-multiarch' (main)
string: command not found
~/.config/fish/functions/fish_prompt.fish (line 1): string replace -r '^'"$real_home"'($|/)' '~$1' (__bobthefish_dirname $current_dir)
                                                    ^
in command substitution
        called on line 74 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_pretty_parent”
        called on line 273 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
        called on line 271 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_path_segment”
        called on line 814 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_prompt_dir”
        called on line 1557 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
        called on standard input

in command substitution
        called on standard input

No command 'string' found, did you mean:
 Command 'strings' from package 'binutils-multiarch' (main)
 Command 'strings' from package 'binutils' (main)
 Command 'spring' from package 'ruby-spring' (universe)
 Command 'spring' from package 'spring' (universe)
string: command not found
~/.config/fish/functions/fish_prompt.fish (line 1): string replace -r '^.*/' '' -- $argv
                                                    ^
in function “__bobthefish_basename”
        called on line 273 of file ~/.config/fish/functions/fish_prompt.fish
        with parameter list “/home/nask/Downloads”

in command substitution
        called on line 271 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_path_segment”
        called on line 814 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_prompt_dir”
        called on line 1557 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
        called on standard input

in command substitution
        called on standard input

 %  /  No command 'string' found, did you mean:Tue 09 Jan 2018 07:10:30 AM CET
 Command 'strings' from package 'binutils-multiarch' (main)
 Command 'strings' from package 'binutils' (main)
 Command 'spring' from package 'ruby-spring' (universe)
 Command 'spring' from package 'spring' (universe)
string: command not found
~/.config/fish/functions/fish_prompt.fish (line 1): string replace -r '/[^/]+/?$' '' -- $argv
                                                    ^
in function “__bobthefish_dirname”
        called on line 76 of file ~/.config/fish/functions/fish_prompt.fish
        with parameter list “/home/nask/Downloads”

in command substitution
        called on line 74 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
        called on line 74 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_pretty_parent”
        called on line 273 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
        called on line 271 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_path_segment”
        called on line 814 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_prompt_dir”
        called on line 1557 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
        called on standard input

in command substitution
        called on standard input

No command 'string' found, did you mean:
 Command 'spring' from package 'spring' (universe)
 Command 'spring' from package 'ruby-spring' (universe)
 Command 'strings' from package 'binutils' (main)
 Command 'strings' from package 'binutils-multiarch' (main)
string: command not found
~/.config/fish/functions/fish_prompt.fish (line 1): string replace -r '^'"$real_home"'($|/)' '~$1' (__bobthefish_dirname $current_dir)
                                                    ^
in command substitution
        called on line 74 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_pretty_parent”
        called on line 273 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
        called on line 271 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_path_segment”
        called on line 814 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_prompt_dir”
        called on line 1557 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
        called on standard input

in command substitution
        called on standard input

No command 'string' found, did you mean:
 Command 'spring' from package 'ruby-spring' (universe)
 Command 'spring' from package 'spring' (universe)
 Command 'strings' from package 'binutils-multiarch' (main)
 Command 'strings' from package 'binutils' (main)
string: command not found
~/.config/fish/functions/fish_prompt.fish (line 1): string replace -r '^.*/' '' -- $argv
                                                    ^
in function “__bobthefish_basename”
        called on line 273 of file ~/.config/fish/functions/fish_prompt.fish
        with parameter list “/home/nask/Downloads”

in command substitution
        called on line 271 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_path_segment”
        called on line 814 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_prompt_dir”
        called on line 1557 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
        called on standard input

in command substitution
        called on standard input

 %  / 

**Comment by bobthecow** [comment]
Yep! bobthefish currently requires Fish 2.3+. To use it with Fish 2.2.x, after installing, please check out the `support/fish-2.2.x` branch:

https://github.com/oh-my-fish/theme-bobthefish/tree/support/fish-2.2.x

```
cd ~/.local/share/omf/themes/bobthefish/
git checkout support/fish-2.2.x
```

Now OMF will keep up with updates to that branch, which doesn't rely on pesky new features like the `string` builtin :)

**Comment by girtsf** [comment]
Could the theme do a fish version check before doing anything else and complain loudly if sees fish < 2.3?

**Comment by bobthecow** [comment]
![screen shot 2018-01-11 at 10 40 47 am](https://user-images.githubusercontent.com/53660/34841099-f0e311e2-f6bb-11e7-943c-60c624f9186e.png)
