### ISSUE TITLE
Powerline broken symbols in VSCode integrated terminal

### ISSUE THREAD

**Issue by aduh95** [oh-my-fish/theme-bobthefish#125]
TL,DR; **What is the font used by this theme?**

I love BobTheFish and I love using VSCode, unfortunately they don't work very well together.

I think it's related to this [vscode#7116](https://github.com/Microsoft/vscode/issues/7116#issuecomment-293072702). The solution described is to add a font setting for VSCode, but it seems BobTheFish uses a different font than the ZSH theme; and I didn't find documented what font I should set.

**Comment by bobthecow** [comment]
Install any of these: https://github.com/ryanoasis/nerd-fonts

**Comment by aduh95** [comment]
Hey @bobthecow, thanks for the feedback. I installed the RobotoMono and the Ubuntu Nerd Fonts, but it didn't change the problem. Maybe I should specify that I already have the correct fonts on the Ubuntu Terminal, the issue I encounter is specific to the VSCode integrated terminal.

In the VSCode settings, I try to set the terminal's font family to "Roboto", "RobotoMono", "'Roboto Mono'", "Ubuntu"; I rebooted my PC a few times, but the problem is still there.

I believe this is because VSCode doesn't find the correct font to use, and I think it would be a good thing to add a note telling which font we're using for those softwares which don't / can't know it.

**Comment by bobthecow** [comment]
You should be selecting the patched version of the font in VSCode, not the regular version.

**Comment by aduh95** [comment]
OK, so make it work by setting the font like this:

```json
"terminal.integrated.fontFamily": "'RobotoMono Nerd Font'"
```

Thanks for your help!

**Comment by tanduong** [comment]
For anyone that landed here: https://dev.to/mattstratton/making-powerline-work-in-visual-studio-code-terminal-1m7

**Comment by mcarpenterjr** [comment]
This looks pretty stale but... 

If you're on Linux and Powerline is already installed on your system, set `"terminal.integrated.fontFamily": "'PowerlineSymbols'"` and it should just work. If you're going to specify another font to use in the terminal, specify it before Powerline.

**Comment by luksurious** [comment]
Just to add to the previous comment for clarity (as it took me some minutes to figure it out), to combine it with a proper monospace font you can write the following:

    "terminal.integrated.fontFamily": "'Ubuntu Mono', 'PowerlineSymbols'",

If you are unsure which font is being used by default, query it in the terminal with 

    gsettings get org.gnome.desktop.interface monospace-font-name

Note, that the font size must be specified with

    "terminal.integrated.fontSize": 16,

**Comment by fsanano** [comment]
The only correct option is to specify the font that you have in the editor you are using.
I used the iTerm2 with zsh and powerLevel9 and there was registered Hack Nerd Font
![image](https://user-images.githubusercontent.com/5524565/53693698-e9b02e80-3dc5-11e9-8785-3b568481ecc4.png)
Then I added
```
"terminal.integrated.fontFamily": "Hack Nerd Font",
```
And now everything is working well.
![image](https://user-images.githubusercontent.com/5524565/53693737-51ff1000-3dc6-11e9-9830-21415f4c5507.png)

**Comment by luispabon** [comment]
For those wanting to use Ubuntu Mono powerline, the font family string is `'Ubuntu Mono derivative Powerline'`

**Comment by aruprakshit** [comment]
For me icons are cut, not being shown properly.

<img width="1166" alt="Screenshot 2019-04-20 at 8 47 40 PM" src="https://user-images.githubusercontent.com/3428463/56459192-a0379500-63ad-11e9-89a7-8571c84845c2.png">

 I have below settings:

<img width="1099" alt="Screenshot 2019-04-20 at 8 49 10 PM" src="https://user-images.githubusercontent.com/3428463/56459201-cc531600-63ad-11e9-840d-f8ac3b544d3a.png">

**Comment by rlquilez** [comment]
Try to change the option "Terminal › Integrated: Renderer Type" to "auto".

**Comment by aruprakshit** [comment]
@rlquilez That fixed it. Awesome.

**Comment by daveclarke** [comment]
I've followed some instructions to enable Powerline in Visual Studio Code integrated terminal on a mac and it all looks good. But the issue I have is the cursor is not appearing at the end of the prompt but in the middle of it.

<img width="452" alt="Screen Shot 2019-06-07 at 1 51 27 PM" src="https://user-images.githubusercontent.com/279084/59076744-aff24500-892b-11e9-8ca3-e15098ff6654.png">

Not sure how to resolve this - any suggestions? I have set the Font Family to 'Menlo for Powerline' with normal font weight and font size of 12.

**Comment by EdisonGonzalez** [comment]
For my case, I have the following and it still does not work well:

1.1. Font: 
![image](https://user-images.githubusercontent.com/20956995/66959623-5f54cc00-f030-11e9-8db8-8b2f9fa869c2.png)

1.2. Profile export (JSON):
![image](https://user-images.githubusercontent.com/20956995/66959715-97f4a580-f030-11e9-9642-89d7888d5a29.png)

2.1. Settings VSCode:
![image](https://user-images.githubusercontent.com/20956995/66959777-b490dd80-f030-11e9-9565-398b74f5cdb7.png)

3.1. iTerm:
![image](https://user-images.githubusercontent.com/20956995/66959851-dc804100-f030-11e9-9807-61573523b18f.png)

3.2. iTerm on VSCode:
![image](https://user-images.githubusercontent.com/20956995/66959888-f457c500-f030-11e9-9ee9-1626e8eca1a9.png)

Thanks for the help, I am attentive to an answer.

**Comment by bobthecow** [comment]
@EdisonGonzalez maybe switch the order around, so Powerline is first and falls back to the others?

**Comment by munjal-patel** [comment]
I am also using the `SourceCodePro+Powerline+Awesome Regular` and having an alignment issue.

**iTerm**
![image](https://user-images.githubusercontent.com/51474446/68517660-56c17100-023d-11ea-8259-1cdf6c62973b.png)

**VSCode Terminal**
![image](https://user-images.githubusercontent.com/51474446/68517699-79ec2080-023d-11ea-8c2b-f5b3016d1ed4.png)

**Comment by theodorenguyen45** [comment]
> I am also using the `SourceCodePro+Powerline+Awesome Regular` and having an alignment issue.
> 
> **iTerm**
> ![image](https://user-images.githubusercontent.com/51474446/68517660-56c17100-023d-11ea-8259-1cdf6c62973b.png)
> 
> **VSCode Terminal**
> ![image](https://user-images.githubusercontent.com/51474446/68517699-79ec2080-023d-11ea-8c2b-f5b3016d1ed4.png)
> 
> ![image](https://user-images.githubusercontent.com/51474446/68517724-94be9500-023d-11ea-93e2-8569b5ad84f8.png)

Having a same issue with this

**Comment by EdisonGonzalez** [comment]
@munjal-patel Thank you for showing me where you had it configured and how you had it configured. It worked for me, the alignment could be the font size.

![image](https://user-images.githubusercontent.com/20956995/68552465-68de1380-03e5-11ea-97ef-2d512d07a077.png)

**Comment by EdisonGonzalez** [comment]
@munjal-patel And if you try what @bobthecow says?

**Comment by EdisonGonzalez** [comment]
@munjal-patel 

It aligns well, look for a due size, here I leave what I needed in the settings.json file (Maybe you are missing the canvas?):

{
...
    "terminal.integrated.shell.osx": "/bin/zsh",
    "terminal.integrated.rendererType": "canvas",
    "terminal.integrated.fontFamily": "'SourceCodePro+Powerline+Awesome Regular'"
}

In fontFamily -> the text source that you can see in your iTerm profile (Iterm2 preferences->Profiles->Text->Font).

**Comment by theodorenguyen45** [comment]
<img width="702" alt="Screen Shot 2019-11-11 at 10 22 51 am" src="https://user-images.githubusercontent.com/47888657/68553467-47c10580-046d-11ea-8007-7b9b0ee1d5e4.png">

I'm facing a same problem too. I also tried to use custom CSS and JS loader but nothing works.
OS: macOS Mojave 10.14.6

**Comment by EdisonGonzalez** [comment]
This is my settings.json complete file:

![image](https://user-images.githubusercontent.com/20956995/68553753-f162b100-03f1-11ea-8a4b-9ec387b54973.png)

Try to find the differences, maybe the order of the parameters?

Try to visualize the parameters by the GUI settings, it will be that these parameters are applied or not.

**Comment by bobthecow** [comment]
>I don't know if something is wrong with my font file?

That's entirely possible. If you swap out for another nerd font does it have the same issue?

**Comment by theodorenguyen45** [comment]
> That's entirely possible. If you swap out for another nerd font does it have the same issue?

I tried with Hack Nerd Font and still facing the same issue

**Comment by wanosoft** [comment]
> > I don't know if something is wrong with my font file?
> 
> That's entirely possible. If you swap out for another nerd font does it have the same issue?

I tried with all Nerd Fonts and Powerline Fonts but still having the same issue.

**Comment by munjal-patel** [comment]
@EdisonGonzalez @bobthecow tried both of your suggestions. No luck. Still I have this:

![image](https://user-images.githubusercontent.com/51474446/68984000-d82b7d00-07c2-11ea-9c9e-ab652b2268ed.png)

**Comment by Konjungamo** [comment]
@munjal-patel have you tried setting the renderer type to dom?
`"terminal.integrated.rendererType": "dom"`
It fixed the alignment for me (at least on the left side of the powerline, the triangles on the right side are still too small).
Left side:
<img width="363" alt="Powerline_Left" src="https://user-images.githubusercontent.com/1979094/69207162-3a7fd700-0b4f-11ea-92e7-fbc17487f02d.png">
Right side:
<img width="202" alt="Powerline_Right" src="https://user-images.githubusercontent.com/1979094/69207179-4370a880-0b4f-11ea-9962-d3a9e9089760.png">

**Comment by emauricio** [comment]
I got a similar problem :( all using the hack font  (installed with brew) 

```
{
   "terminal.integrated.fontFamily": "'Hack Nerd Font'",
    "terminal.integrated.rendererType": "dom",
    "terminal.integrated.fontSize": 14,
}
```
mac terminal 
![image](https://user-images.githubusercontent.com/7945345/69437487-bf086a80-0d86-11ea-8648-47cbee2e2611.png)
vs code - dom
![image](https://user-images.githubusercontent.com/7945345/69437678-1a3a5d00-0d87-11ea-9629-5fc339fa6c94.png)
vs code - canvas|auto
![image](https://user-images.githubusercontent.com/7945345/69437798-49e96500-0d87-11ea-9d2f-f2609da1a77a.png)
vscode hack font disabled + dom
![image](https://user-images.githubusercontent.com/7945345/69438753-f6781680-0d88-11ea-80fc-50ea80630144.png)
vscode hack font disabled + canvas
![image](https://user-images.githubusercontent.com/7945345/69438805-17d90280-0d89-11ea-90bf-8d8929d7e0a4.png)
webstorm
![image](https://user-images.githubusercontent.com/7945345/69438514-810c4600-0d88-11ea-9249-ccf6238e06df.png)

**Comment by munjal-patel** [comment]
@Konjungamo yes, that was it! Switching to `dom` did fix it. Thanks a lot!

**Comment by viirak** [comment]
Instruction in the following post works for me
https://medium.com/@hippojs.guo/vs-code-fix-fonts-in-terminal-761cc821ef41

**Comment by YIREN1** [comment]
after I tried everything that mentioned in the comments above, nothing worked...I kept trying playing around with `"terminal.integrated.fontFamily": "FiraCode Nerd Font"` however when I set `"editor.fontFamily": "FiraCode Nerd Font"`, it worked...I thought this setting is only for editor. But for some reason we have to modify both? It's probably a vscode thing...

**Comment by ax0n-pr1me** [comment]
I have read this entire thread and I am 90% sure I have tried everything recommended here and in the included links but I can still not get the icons to work in VSCode.

OS: Ubuntu 18.04
Terminal: zsh / Powerlevel10k

Ideally I would be using the Blex patched font, but at this point getting anything to render the icons correctly would be a nice start. 

from my terminal proper:
![image](https://user-images.githubusercontent.com/49602733/79822959-ae691a00-834f-11ea-934e-dd08522736eb.png)

from vscode:
![image](https://user-images.githubusercontent.com/49602733/79823004-cf316f80-834f-11ea-9580-75329a7914aa.png)

Here is the section in the JSON, but I have tried what feels like every possible combination of terminal and editor font families... 
```
    "editor.fontFamily": "'IBM Plex Mono",
    "terminal.integrated.shell.linux": "/usr/bin/zsh",
    "terminal.integrated.fontFamily": "'IBM Plex Mono'",
    "terminal.integrated.rendererType": "auto",
```

and in my terminal settings:
![image](https://user-images.githubusercontent.com/49602733/79823174-57177980-8350-11ea-9900-3e92a9eb93d0.png)

Anyone gotten Plex to work on Ubuntu and VSCode?

Cheers,

**Comment by SGarcia710** [comment]
> @munjal-patel
> 
> It aligns well, look for a due size, here I leave what I needed in the settings.json file (Maybe you are missing the canvas?):
> 
> {
> ...
> "terminal.integrated.shell.osx": "/bin/zsh",
> "terminal.integrated.rendererType": "canvas",
> "terminal.integrated.fontFamily": "'SourceCodePro+Powerline+Awesome Regular'"
> }
> 
> In fontFamily -> the text source that you can see in your iTerm profile (Iterm2 preferences->Profiles->Text->Font).

`"terminal.integrated.fontFamily": "'SourceCodePro+Powerline+Awesome Regular'"` With this line it worked for me! Thanks!

**Comment by arindas** [comment]
Setting this in my init.fish worked for me.
```
# set locale
set -xg LC_ALL en_US.UTF-8
set -xg LANG en_US.UTF-8
```

**Comment by romerofrancisco** [comment]
I just used 

"terminal.integrated.fontFamily": "'Hack'"

Looks great.

**Comment by Wusinho** [comment]
![image](https://user-images.githubusercontent.com/67179149/107128976-e5cd9680-688f-11eb-9cd1-75bcbadf9f52.png)
Anyone can give me a hand?

**Comment by theodorenguyen45** [comment]
> ![image](https://user-images.githubusercontent.com/67179149/107128976-e5cd9680-688f-11eb-9cd1-75bcbadf9f52.png)
> It only happens when I open then terminal from VSC.

It should be "'Hack'". You just missed a single quote

**Comment by theodorenguyen45** [comment]
@Wusinho It should be "'Hack'". You just missed a single quote.

Btw, what theme are you using?

**Comment by Wusinho** [comment]
> @Wusinho It should be "'Hack'". You just missed a single quote.
> 
> Btw, what theme are you using?
@theodorenguyen45
I really don't know but I like it, I was just following a guide on Youtube.
The issue was the incomplete name, it was "Hack Nerd Font"

![image](https://user-images.githubusercontent.com/67179149/107134893-14fdfb00-68c4-11eb-9714-e69e764ca22f.png)

**Comment by theodorenguyen45** [comment]
@Wusinho 
These line will tell you what theme and color you are using
![image](https://user-images.githubusercontent.com/47888657/107139270-af624b00-6965-11eb-85b5-8c6224216837.png)

**Comment by Wusinho** [comment]
@theodorenguyen45
I'm sorry, Where is that?

**Comment by ullaskunder3** [comment]
@Wusinho 
In the setting OR try `Ctrl+,` then on top right `Open Settings (JSON)`

`Ctrl+f` to search type `workbench.colorTheme` if available change it or add

![image](https://user-images.githubusercontent.com/66258652/132183877-1843a658-fec7-404e-ab3f-f5b3952c0381.png)
