### ISSUE TITLE
theme_display_user does not honor default_user

### ISSUE THREAD

**Issue by letheed** [oh-my-fish/theme-bobthefish#129]
Just ran `omf update` and my username now appears in the prompt.

I believe [this](https://github.com/oh-my-fish/theme-bobthefish/blob/master/fish_prompt.fish#L525) should be the culprit. It should probably be something like:

```fish
[ \( "$theme_display_user" = 'yes' -a "$USER" != "$default_user" \) -o -n "$SSH_CLIENT" ]
```

**Comment by bobthecow** [comment]
I think the logic was wrong before :)

Your user will now show if _any_ of the following are true:

- you set `theme_display_user` to "yes" (i.e. opted in to "show my username")
- you set a `default_user`, and the current user is not that user
- you're SSHd into another machine

If you want the old behavior back, you can stop setting `theme_display_user` and it'll go back to the old way.

You _could_ argue that there's no longer a way to opt out of the username segment entirely, and you'd be right. But it doesn't sound like that's what you're looking for?

**Comment by letheed** [comment]
Ah, so `default_user` implies `theme_display_user` now... I see, well that's a bit counter intuitive, I think. I found the old behavior more logical.

Regardless, thank you for pointing it out. And thank you for your theme!

**Comment by schaten** [comment]
> there's no longer a way to opt out of the username segment entirely

It would be great if you could either change this or add a hint in the readme that `theme_display_user` and `theme_display_hostname` don't apply for ssh-sessions.

I would propose adding a variable `theme_display_ssh`. The effect would be that, if:
- `"$theme_display_user" = 'yes'`: Always show username, independent of `theme_display_ssh`
- `"$theme_display_user" = 'no'` and `"$theme_display_ssh" = 'yes'`: Show username only when ssh-session is detected.
- `"$theme_display_user" = 'no'` and `"$theme_display_ssh" = 'no'`: Never show username.
The same applies for the hostname.

Pull Request #139. :)

**Comment by bobthecow** [comment]
Closing as it's now possible (and more obvious via the docs!) to configure all permutations thanks to #139.

Thanks @schaten!
