### ISSUE TITLE
(informative git prompt?) : Number of Changed files

### ISSUE THREAD

**Issue by gkatsanos** [oh-my-fish/theme-bobthefish#130]
Is it possible (how?) to show the number of changed files? ( fish_git_prompt_show_informative_status )

**Comment by bobthecow** [comment]
there are currently two options to add more verbosity:

```fish
set -g theme_display_git_ahead_verbose yes
set -g theme_display_git_dirty_verbose yes
```

the one you're looking for is probably "dirty"?

**Comment by gkatsanos** [comment]
Doesn't seem like it does anything else by show the (*) and not the actual precise number of changed files. (can't copy paste, the icon font is missing)

 ~/frontend   master *$  set -g theme_display_git_dirty_verbose yes  3645ms  Wed Mar 21 15:27:39 2018
 ~/frontend   master *$ 

**Comment by bobthecow** [comment]
That's strange. Are you updated to the latest version of bobthefish?

![screen shot 2018-03-21 at 10 11 27 am](https://user-images.githubusercontent.com/53660/37725510-5f94d35e-2cf0-11e8-9b0a-2f1e89cda994.png)

**Comment by gkatsanos** [comment]
I've set it up in February - did you change something in between? By the way the screenshots in the documentation also do not show a number of modified files.
Are we talking about the same thing?

**Comment by gkatsanos** [comment]
I updated OMF, removed and reinstalled bobthefish.
Now I see even less info than before, even after setting 
```sh
set -g theme_display_git_ahead_verbose yes
set -g theme_display_git_dirty_verbose yes
```

Do I need to manually modify or override any files?

**Comment by gkatsanos** [comment]
![image](https://user-images.githubusercontent.com/1768834/37779187-1c112f86-2dec-11e8-862a-97f2a15a6758.png)
ok, now I see the number of changed files - but I dont see the branch name

**Comment by bobthecow** [comment]
see 4ac7f3c5d7ff9f75546c8382297622345e819ea6

**Comment by nomstradamus** [comment]
what is that $... and how do we fix it .

**Comment by gkatsanos** [comment]
Installed again a new setup with OMF and bobthefish, again don't see number of added files.. 

<img width="282" alt="Screenshot 2019-08-01 at 12 09 43" src="https://user-images.githubusercontent.com/1768834/62285147-556df480-b455-11e9-92d4-1e5d3679a782.png">

```
cat ~/.config/fish/config.fish                                                                              Thu Aug  1 12:09:35 2019
#     set -g theme_display_git no
set -g theme_display_git_dirty yes
set -g theme_display_git_untracked yes
set -g theme_display_git_ahead_verbose yes
set -g theme_display_git_dirty_verbose yes
set -g theme_display_git_stashed_verbose yes
set -g theme_display_git_master_branch yes
#     set -g theme_git_worktree_support yes
#     set -g theme_display_vagrant yes
#     set -g theme_display_docker_machine no
#     set -g theme_display_k8s_context yes
#     set -g theme_display_hg yes
#     set -g theme_display_virtualenv no
set -g theme_display_ruby yes
#     set -g theme_display_user ssh
#     set -g theme_display_hostname ssh
#     set -g theme_display_vi no
#     set -g theme_display_nvm yes
#     set -g theme_avoid_ambiguous_glyphs yes
#     set -g theme_powerline_fonts no
#     set -g theme_nerd_fonts yes
#     set -g theme_show_exit_status yes
#     set -g default_user your_normal_user
#     set -g theme_color_scheme dark
#     set -g fish_prompt_pwd_dir_length 0
#     set -g theme_project_dir_length 1
#     set -g theme_newline_cursor yes
set -g theme_display_git_ahead_verbose yes
set -g theme_display_git_dirty_verbose yes
set -g theme_display_git_master_branch yes
rvm default
```
`Oh My Fish version 6`

**Comment by gkatsanos** [comment]
for some reason it works but you need to switch shells ..
