### ISSUE TITLE
git status always shows staged icon even when there are no staged changes

### ISSUE THREAD

**Issue by fabiomargarido** [oh-my-fish/theme-bobthefish#134]
Commit da2cd2eac4148d492a7b7ae2067dd610072bbf8f seems to have broken the 'staged' indicator for me. I always get the diskette icon (using nerd fonts) even when there are no staged changes on multiple repos.

Let me know if I can provide any further info.

**Comment by bobthecow** [comment]
Oops. Sorry about that. It should be fixed now :)

**Comment by fabiomargarido** [comment]
Just updated and verified that the staged icon is now shown correctly when needed.

Thanks for the quick fix!

**Comment by bobthecow** [comment]
No problem. Thank you for reporting the issue.
