### ISSUE TITLE
Usage with fundle overrides fish_greeting

### ISSUE THREAD

**Issue by simonszu** [oh-my-fish/theme-bobthefish#136]
Hi,

i have just switched from the Gentoo theme to bobthefish, and maybe it is just me, or there are some problems when using bobthefish with fundle. I am speaking about the `fish_greeting`. I like to create my own greeting, so i created the function like stated in the readme. However, the greeting remains the old bobthefish greeting - and executing `fish_greeting` manually just echoes bobthefish's default greeting. 

I am referencing bobthefish just normally in my `config.fish`'s fundle block, but i have the following suspiction: Since bobthefish is loaded as a plugin after fish starts, fish loads the custom `fish_greeting` right after startup - and loads bobthefish then, which itself overrides the custom greeting with its own default greeting. 

In https://github.com/oh-my-fish/theme-bobthefish/issues/18 there was said that bobthefish should work with all plugin managers, and that we should let you know if there are any problems - so, i have a problem ;)

**Comment by simonszu** [comment]
This occurs for other files as well, e.g. `fish_right_prompt`.

**Comment by bobthecow** [comment]
To be honest, I don't use fundle, so I can't speak to how they support or expect function overrides to work. I'd suggest opening an issue there.

If there's a change I can/should make to bobthefish to make it work better, I'm more than happy to :)

**Comment by tuvistavie** [comment]
@bobthecow Is there any reason why `fish_greeting` is in the root directory and not in the functions directory? How does omf loads the `fish_greeting` function?
Thanks.

**Comment by bobthecow** [comment]
omf (and i believe most if not all other fish plugin managers) treat the root of a theme repo as a functions directory as well.

**Comment by tuvistavie** [comment]
I see, thanks for the information. fundle only adds the `functions` directory to the path and sources the files in the root directory, which is why it is not working as expected.
I will see what I can do about it, thanks!

**Comment by thalesmello** [comment]
Fixed by https://github.com/danhper/fundle/pull/48

It's a problem regarding the difference in behaviour between fundle and oh-my-fish.
Rather than treating the plugin root folder as a function folder, it actually sources all
of the files. Hence, the created functions were interpreted by fish as dynamic function
creating, which gave them higher precedence over functions defined in files.

**Comment by thalesmello** [comment]
Since it's a problem with fundle, I believe this issue can actually be closed.

**Comment by scorphus** [comment]
@simonszu, please follow danhper/fundle#48 up.

Thanks, @thalesmello!
