### ISSUE TITLE
Python virtualenv prompt breaks with PyPy

### ISSUE THREAD

**Issue by cvitan** [oh-my-fish/theme-bobthefish#137]
When using PyPy 5.10.1, the __bobthefish_virtualenv_python_version breaks in the switch as the python version command returns two lines. Removing the ^ character  before the pipe resolves the issue.

Example:
```
>> python --version ^| tr '\n' ' '
Python 3.5.3 (3f6eaa010fce, Jan 11 2018, 05:27:47)
[PyPy 5.10.1 with GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
>> python --version | tr '\n' ' '
Python 3.5.3 (3f6eaa010fce, Jan 11 2018, 05:27:47) [PyPy 5.10.1 with GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] 
```
 
Affected line:
https://github.com/oh-my-fish/theme-bobthefish/blob/master/fish_prompt.fish#L653

**Comment by bobthecow** [comment]
Thank you for reporting. I couldn’t reproduce your issue, but it _should_ be fixed now. Do you mind pulling and testing it out?

**Comment by cvitan** [comment]
That did the job, thanks for the quick response!

**Comment by bobthecow** [comment]
Great. Thank you!
