### ISSUE TITLE
Remove Kernel Info

### ISSUE THREAD

**Issue by xtramon** [oh-my-fish/theme-bobthefish#138]
Hi,
it's not really an issue with the theme. i am to stupid to find the right option,

When i start a terminal (urxvt) it shows the linux kernel version, the time i opened the terminal, etc.
How can i remove this?

**Comment by bobthecow** [comment]
That's coming from [bobthefish's `fish_greeting` function](https://github.com/oh-my-fish/theme-bobthefish/blob/master/fish_greeting.fish). If you don't like that one, you can define your own. See [the "Overrides" section of the readme](https://github.com/oh-my-fish/theme-bobthefish#overrides) for more info!

**Comment by xtramon** [comment]
Thanks! 
That helped.
