### ISSUE TITLE
Google Cloud SDK

### ISSUE THREAD

**Issue by maarteNNNN** [oh-my-fish/theme-bobthefish#141]
I've used Google Cloud SDK in my terminal and now my project keeps appearing in my terminal

```shell
 gke_totaxxxxx-197100_southamerica-east1-a_xxx  ~  exit    Tue 16:36
[maarten@ArchieLaptop ~]$ fish
Linux ArchieLaptop 4.15.9-1-ARCH x86_64
 16:36:42 up 31 min,  1 user,  load average: 1.22, 1.00, 0.75
 gke_totxxxxxx-197100_southamerica-east1-a_xxx  ~  exit    Tue 16:36
```

How can I remove this? It's so annoying.

**Comment by bobthecow** [comment]
Google Cloud SDK sets a Kubernetes context in your shell. To disable it, you can either clear the Kubernetes setup (if you're not actually using it) or disable Kubernetes support in bobthefish.

To do the latter, add this to your fish config:

```
set -g theme_display_k8s_context no
```

**Comment by maarteNNNN** [comment]
@bobthecow Thank you very much! I was searching how to clear out the output from Google Cloud SDK, most docs I found was inside the console on there website.

**Comment by bobthecow** [comment]
There were enough issues like this that I've disabled the kubernetes segment by default :)

**Comment by maarteNNNN** [comment]
@bobthecow I think it's better that way indeed. It's pretty annoying.
