### ISSUE TITLE
Theming 

### ISSUE THREAD

**Issue by domoritz** [oh-my-fish/theme-bobthefish#142]
Could you update the readme to explain how to create a theme? It still says that I should use `user`, which I believe is deprecated.

**Comment by bobthecow** [comment]
Oh, sorry about that. It was just changed. I should update the documentation.

If you were _previously_ using a user-defined color scheme, it would print out super handy instructions for how to migrate it.

Check out the output from that notice here:

https://github.com/oh-my-fish/theme-bobthefish/blob/master/functions/__bobthefish_colors.fish#L504-L531

i.e.

```fish
function bobthefish_colors -S -d 'Define a custom bobthefish color scheme'

  # optionally include a base color scheme...
  ___bobthefish_colors default

  # then override everything you want! note that these must be defined with `set -x`
  set -x color_initial_segment_exit  $__color_initial_segment_exit
  set -x color_initial_segment_su    $__color_initial_segment_su
  set -x color_initial_segment_jobs  $__color_initial_segment_jobs
  set -x color_path                  $__color_path
  set -x color_path_basename         $__color_path_basename
  set -x color_path_nowrite          $__color_path_nowrite
  set -x color_path_nowrite_basename $__color_path_nowrite_basename
  set -x color_repo                  $__color_repo
  set -x color_repo_work_tree        $__color_repo_work_tree
  set -x color_repo_dirty            $__color_repo_dirty
  set -x color_repo_staged           $__color_repo_staged
  set -x color_vi_mode_default       $__color_vi_mode_default
  set -x color_vi_mode_insert        $__color_vi_mode_insert
  set -x color_vi_mode_visual        $__color_vi_mode_visual
  set -x color_vagrant               $__color_vagrant
  set -x color_username              $__color_username
  set -x color_hostname              $__color_hostname
  set -x color_rvm                   $__color_rvm
  set -x color_virtualfish           $__color_virtualfish
  set -x color_virtualgo             $__color_virtualgo
  set -x color_desk                  $__color_desk
end
```

Copy and paste that into a file called `bobthefish_colors.fish` in your `$fish_function_path` (probably `~/.config/fish/functions/bobthefish_colors.fish`) and replace the variables with the colors you want.

If you want to use a base color scheme and just tweak a few things, you can change the `__bobthefish_colors default` line to reference any of the built-in color schemes. Then you can comment out or delete the lines for colors you don't want to override.

To test the output while creating your color scheme, you can run `bobthefish_display_colors`. To see the built-in color schemes, run `bobthefish_display_colors --all` :)

**Comment by domoritz** [comment]
Yeah, I came across the error message. It was indeed very useful. Thank you for thinking ahead there. I was just worried that it's hard to get to unless you already have a legacy theme. The instructions above are great for the readme.

**Comment by bobthecow** [comment]
Documentation for custom color schemes have been added to the wiki :) 

https://github.com/oh-my-fish/theme-bobthefish/wiki/Custom-color-schemes
