### ISSUE TITLE
Error on every action

### ISSUE THREAD

**Issue by StefanPahlplatz** [oh-my-fish/theme-bobthefish#143]
**Fish version:** 2.6.0
**Oh-my-fish version:** 6
**OS:** Ubuntu 17.10

I'm getting this error on every action that I do in the terminal:

```sh
__parse_current_folder: command not found
~/.config/fish/functions/fish_prompt.fish (line 1): 
__parse_current_folder
^
in command substitution
	called on line 42 of file ~/.config/fish/functions/fish_prompt.fish

in function “pre_prompt”
	called on standard input

in event handler: handler for generic event “fish_prompt”

__format_time: command not found
~/.config/fish/functions/fish_prompt.fish (line 1): 
__format_time $CMD_DURATION $pure_command_max_exec_time
^
in command substitution
	called on line 42 of file ~/.config/fish/functions/fish_prompt.fish

in function “pre_prompt”
	called on standard input

in event handler: handler for generic event “fish_prompt”
```

After restarting fish everything works fine. It's just the first time after installing the theme that I got this error.

**Comment by bobthecow** [comment]
Those "command not found" function names aren't part of bobthefish. I imagine you've got a `fish_prompt` from another theme mixed in with things?

Deleting or renaming `~/.config/fish/functions/fish_prompt.fish` will probably fix your issue, but I'd be interested to know how you got in this state. `ls -al ~/.config/fish/functions` to see where it's coming from? What are you using for Fish package management?

**Comment by StefanPahlplatz** [comment]
My default shell is zsh, so I entered fish just by running ```fish```, after I ran ```omf install bobthefish``` I got the error. It was fixed by closing out of the shell and starting it again.

**Comment by bobthecow** [comment]
Interesting. Were you using a different OMF theme before changing to bobthefish?

**Comment by bobthecow** [comment]
It looks like switching themes in general is broken with omf. Running `omf reload` after changing themes seems to fix it, but I have to do it after changing to or from any theme.

**Comment by bobthecow** [comment]
Thanks for your help!
