### ISSUE TITLE
Changed prompt after Minikube installation

### ISSUE THREAD

**Issue by denisgarci** [oh-my-fish/theme-bobthefish#147]
Thanks for this great theme. I recently installed minikube on my Mac and I have the following prompt:
<img width="153" alt="screen shot 2018-04-10 at 5 03 13 pm" src="https://user-images.githubusercontent.com/5141673/38589663-348a98e6-3ce1-11e8-91cb-310914c6e96d.png">

I tried to play with `set -g theme_display_virtualenv no` but didn't manage to remove the `minikube` that was added to my prompt. Any idea how to remove that from the prompt?

**Comment by denisgarci** [comment]
@bobthecow It worked great thank you!

**Comment by bobthecow** [comment]
There were enough issues like this that I've disabled the kubernetes segment by default :)
