### ISSUE TITLE
Emacs tramp doesn't recognise the shell prompt

### ISSUE THREAD

**Issue by binshengliu** [oh-my-fish/theme-bobthefish#148]
If the remote server use fish shell and bobthefish theme, emacs would hang when opening a file through ssh because it doesn't recognise the prompt.

Just found a solution [here](https://www.gnu.org/software/emacs/manual/html_node/tramp/Frequently-Asked-Questions.html) in the `tramp does not connect to the remote host` section. Perhaps you want to incorporate this in `fish_prompt`.

This is what I found works.

``` shell
function fish_prompt -d 'bobthefish, a fish theme optimized for awesome'
  if test $TERM = "dumb"
    echo "\$ "
    return 0
  end
  # other stuff
end
```

**Comment by bobthecow** [comment]
This is probably something best solved at your end. Adding the following to the end of your `config.fish` should do the trick:

```fish
if test "$TERM" = "dumb"
  function fish_prompt
    echo "\$ "
  end

  function fish_right_prompt; end
  function fish_greeting; end
  function fish_title; end
end
```

**Comment by binshengliu** [comment]
True. Thanks!

**Comment by federkamm** [comment]
For me this only partly solved the problem.  I got still strange behaviour and lagging with TRAMP.  I'm a little bit harsher and use in my config.fish:

    if test "$TERM" = "dumb"
        exec sh
    end

Now, everything runs smoothly again.

**Comment by azzamsa** [comment]
@federkamm solution fixes Trump issue. But it make all my function that contains `start-process` fails.

So I go with @bobthecow solutions.

**Comment by aegithalos** [comment]
This breaks pdf export in org mode, since pdflatex is called like
` fish -c "pdflatex ..." `from emacs.

 I had a hard time to find this out :)
