### ISSUE TITLE
Bug: newest version from omf caught several bat behaviours

### ISSUE THREAD

**Issue by the0demiurge** [oh-my-fish/theme-bobthefish#153]
![screenshot from 2018-05-04 17-36-55](https://user-images.githubusercontent.com/11363529/39621751-61687542-4fc2-11e8-941e-a757c2dfdc85.png)

everything is wrong
```
> fish --version
fish, version 2.7.1
```

**Comment by bobthecow** [comment]
Those functions it's looking for aren't part of bobthefish. Switching themes seems to be broken on omf right now :(

See #143

You should be able to fix this by running `omf reload` after switching themes, or by opening a new shell.

**Comment by the0demiurge** [comment]
Although I can reload fish, the fish prompt was not right: it shows a rather long string
`ssshare/api-starter-us-west-2-openshift-com:xxxxx`, which wasn't shown before I updated bobthefish :(

**Comment by bobthecow** [comment]
Yeah :(

That long string is your current Kubernetes context. See https://github.com/oh-my-fish/theme-bobthefish/issues/141#issuecomment-374820056 for more info.

I might make showing Kubernetes context opt-in rather than opt-out, since a bunch of people seem to have a default context hanging around that they don't know or care about.

**Comment by the0demiurge** [comment]
```bash
>>> __bobthefish_path_segment "$PWD"


set_color: Expected argument for option -b
~/.config/fish/functions/fish_prompt.fish (line 268): 
  set_color -b $bg $fg $argv
  ^
in function “__bobthefish_start_segment”
	called on line 296 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_path_segment”
	called on standard input


       set_colorset_color - set the terminal color
        -

   Synopsis
       set_color [OPTIONS] VALUE

set_color: Type “help set_color” for related documentation

 set_color: Expected argument for option -b
~/.config/fish/functions/fish_prompt.fish (line 312): 
  set_color -b $segment_basename_color
  ^
in function “__bobthefish_path_segment”
	called on standard input


       set_colorset_color - set the terminal color
        -

   Synopsis
       set_color [OPTIONS] VALUE

set_color: Type “help set_color” for related documentation

/ ⏎           
```

**Comment by bobthecow** [comment]
`__bobthefish_path_segment` (and the rest of the `__bobthefish*` methods) isn't meant to be called on its own. Mind if I ask what you're doing that for? :)

**Comment by the0demiurge** [comment]
I wanted to find what's wrong in my fish_prompt and caught that exception:)

I wasn't running a Kumbernets or so, I'm simply running on a gnome-terminal on my laptop, but why was that long string showing?

**Comment by bobthecow** [comment]
Kubernetes is used by a ton of things, and it leaves a default context laying around even if you just try it once. The usual suspects are things like trying the Google Cloud SDK. In your case it looks like it might be openshift related?

**Comment by the0demiurge** [comment]
Yes, I was using openshift and removing `.kube` fixed this issue
Thank You!

**Comment by bobthecow** [comment]
There were enough issues like this that I've disabled the kubernetes segment by default :)
