### ISSUE TITLE
Add a theme_display_greeting boolean

### ISSUE THREAD

**Issue by paride** [oh-my-fish/theme-bobthefish#158]
I know: the greeting can be disabled by setting `fish_right_prompt` to an empty function, as explained in the README. But changes to `fish_greeting.fish` are lost every time the theme is updated (at least this happen when using [fisherman](https://github.com/fisherman)). A `theme_display_greeting` variable (analogous to `theme_display_date`) would solve the issue.

**Comment by patrickf3139** [comment]
So in OMF, user-defined functions in the functions folder are not overwritten by OMF when plugins are installed/updated?

**Comment by bobthecow** [comment]
Yep! OMF uses the `$fish_function_path` pretty extensively, and it works just like regular `$PATH`, so it's possible for later things (like user-defined functions) to override earlier things (like themes and plugins) which in turn can override defaults (like the fish-provided `fish_prompt`).
