### ISSUE TITLE
Spurious character when displaying virtualenv

### ISSUE THREAD

**Issue by ksmets** [oh-my-fish/theme-bobthefish#16]
There seems to be an issue with displaying the default arrow separator when displaying virtualenvs. As there is a spurious 2 and > after the ◰ character. I expected arrow separators like the remainder of the status bar.

I use Ubuntu Mono derivative Powerline for non-ascii fonts and Monoco for the regular font in iTerm and use the default theme settings.

<img width="795" alt="screen shot 2015-11-19 at 17 31 17" src="https://cloud.githubusercontent.com/assets/2758297/11276729/7fe24d38-8ee3-11e5-8318-96c7a655ab96.png">

**Comment by ksmets** [comment]
Ok. Found out that the 2 is the python version. Which is nice, but how can I change the > character. Or is this by design?

**Comment by bobthecow** [comment]
That character is what happens when you have two segments of the same color next to each other. It probably needs a space before it in this case.

**Comment by ksmets** [comment]
I now see a space character between python version and >, not a segment sepator.

<img width="697" alt="screen shot 2016-01-15 at 09 49 19" src="https://cloud.githubusercontent.com/assets/2758297/12349102/499b2bbc-bb6d-11e5-87d7-88330b4f1b39.png">

**Comment by bobthecow** [comment]
Yep, that's exactly what you're supposed to see.

There are two types of segment separators: the kind between two colors, and the kind between two segments of the same color. In this case it's the latter, because the two segments are related to each other :)
