### ISSUE TITLE
Truncated branch name

### ISSUE THREAD

**Issue by bennypowers** [oh-my-fish/theme-bobthefish#161]
👋! Great theme, I've been happily using it for years. Thank you!

My team uses issue-name branches, so we could have a branch name like 

```
4-when-switching-from-portrait-to-landscape-current-scroll-should-be-respected
```

In those cases, the prompt can overflow the screen. Prompt should truncate branch name after some number of chars.

Best,
B

**Comment by gerardsimons** [comment]
Why was this closed? I also have this issue, though not as extremely long as this guy, even a relatively short feature branch could severely clog up the prompt. Any tips / ideas?

**Comment by gerardsimons** [comment]
Cool, thanks!
