### ISSUE TITLE
Red NO after ruby install through asdf-vm

### ISSUE THREAD

**Issue by williamokano** [oh-my-fish/theme-bobthefish#167]
Hi, after installing ruby through asdf-vm my prompt is showing a "No" stuff.

Here's the image. Anyone knows what this  could be so I can fix, or disable, it?

![image](https://user-images.githubusercontent.com/5909442/45398357-27ec4280-b61a-11e8-923f-5d5bc1841247.png)

**Thanks in advance**

**Comment by bobthecow** [comment]
what is the output of `asdf current ruby`?

**Comment by bobthecow** [comment]
(that red thing is showing your current ruby version. but "no" isn't a great ruby version, so i'd like to understand why it's showing that)

**Comment by williamokano** [comment]
@bobthecow Hi justin, this problem is only ocurring on my work laptop. I'll give the feedback tomorrow :) and thanks for the quick answer

**Comment by bobthecow** [comment]
thanks. no problem!

**Comment by williamokano** [comment]
The output was `No version set for ruby...`. Found the problem. Although the ruby was indeed installed, asdf wasn't recognizing him. Just cleaned everything from asdf, reinstalled, added ruby plugin, installed version and set as global and now everything is working fine.

@bobthecow thanks for the help!
