### ISSUE TITLE
Feature request: show username when in sudo shell

### ISSUE THREAD

**Issue by Strayer** [oh-my-fish/theme-bobthefish#170]
It would be nice to be able to see the current username when in a sudo shell (`sudo -s`), like with user@hostname for SSH. The relevant environment variable could be `SUDO_USER=...`.

**Comment by FMeinicke** [comment]
Hi! I know this issue has been around for over a year now, but if you'd still like to have this feature implemented, I would be happy to look into this. I think this is a really nice to have functionality!

How do you imagine the prompt to look like? I don't really know what you mean with *"like with user@hostname for SSH"*. Do you mean something similar to `normal_user@root`?

**Comment by Strayer** [comment]
I have to admit that I'm not using bobthefish anymore 😰 But yes, when I created the issue I did imagine something like that. I have two use-cases:

1. multiple users on my MacBook (with only one being able to run homebrew to manage software, thus forcing me to use sudo to switch to another non-root user quite often). It can be quite painful to have a long-running, long forgotten sudo session in a terminal tab and not realizing that I'm running something with another user.

2. using `sudo -s` to become root on remote systems that I can only SSH into with a non-root user

I'd assume this would be helpful to other people too, even though I switched to another theme.

**Comment by FMeinicke** [comment]
Ok, I see what you mean. I also think this feature is quite helpful for other people, as well. 


So, I think I'm going to use the `normal_user@root` syntax, since you're not averse to it.

**Comment by bobthecow** [comment]
I just added username support when sudoing! Thanks for the nudge @FMeinicke 🙂

**Comment by FMeinicke** [comment]
No prob! 😄
Happy to help anyways
