### ISSUE TITLE
Any ZSH equivalent theme?

### ISSUE THREAD

**Issue by nipunsadvilkar** [oh-my-fish/theme-bobthefish#173]
I would like to have the same functionalities - color scheme, auto suggestions, syntax highlighting, shrink (abbreviated) path functionality in [agnoster zsh theme](https://github.com/agnoster/agnoster-zsh-theme).

I was able to reproduce auto suggestions, syntax highlighting in zsh but color scheme and shrink-path is not yet done. Tried [plugins/shrink-path](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/shrink-path) but still unable to mimic bobthefish functionality.

@bobthecow : Any inputs would be very much helpful!

**Comment by bobthecow** [comment]
I'm sorry, I haven't used zsh in several years. I'm afraid I won't be much help.

**Comment by nipunsadvilkar** [comment]
No issues thanks for replying. If I happen to convert it to zsh equivalent..will update you

**Comment by theqoobee** [comment]
Hey @nipunsadvilkar, I was looking for the same thing when I came across this thread, so any updates or did you find another solution?
