### ISSUE TITLE
Can't change color scheme or other options

### ISSUE THREAD

**Issue by tiagocborg** [oh-my-fish/theme-bobthefish#175]
I installed everything, is looking good, but I can't run  ```set -g``` to change any configuration.  Whenever I run the command nothing happens, but the env var is being set correctly. Even running ```omf reload``` doesn`t help.

<img width="336" alt="captura de tela 2018-10-20 as 06 14 35" src="https://user-images.githubusercontent.com/6026596/47253850-bb8e0b80-d42f-11e8-868a-c6354a2496f4.png">

I am using Mac OS Mojave with iTerm2.

Any hint?

**Comment by tiagocborg** [comment]
Nevermind. It was a issue with my env

**Comment by dwrz** [comment]
@tiagocborg Any chance you remember how you resolved this? I seem to be running into the same issue.
