### ISSUE TITLE
Prompt seems to be broken on mercurial repositories

### ISSUE THREAD

**Issue by ruipacheco** [oh-my-fish/theme-bobthefish#178]
This is how my prompt looks like on a git repo:
`~/P/a/waitress  ⎇  `

This is how my prompt looks like on an hg repo:
`~/c/databaseclient  ☿  ⎇ default @   cpp/ninja `

Notice how on hg the repo flags are in the middle of the path. Also, I don't have the fancy fonts installed and am using the latest macOS with the built-in Terminal.

**Comment by bobthecow** [comment]
If you're in a subdirectory called `cpp/ninja` under the repo root, then this is rendering as expected. Bobthefish adds the segment with the repo status in the middle of the path, so…

`~/abbreviated/path/to/repo [ repo status ] path/relative/to/repo`
