### ISSUE TITLE
Prompt overlapping previous line of output

### ISSUE THREAD

**Issue by devjgm** [oh-my-fish/theme-bobthefish#180]
I recently installed fish and the bobthefish theme in Crostini on a Pixelbook chromebook. One UI issue I see is that the prompt overlaps the previous line of output. See this [screenshot](https://drive.google.com/file/d/1uVu4giDP838v9-zxKkGjuMA4YHam4-i0/view?usp=sharing).

```shell
Linux penguin 4.14.74-07776-gac52e5f750c8 x86_64
 13:15:37 up 48 min,  2 users,  load average: 0.18, 0.10, 0.04

$ uname -a
Linux penguin 4.14.74-07776-gac52e5f750c8 #1 SMP PREEMPT Thu Dec 6 17:36:39 PST 2018 x86_64 GNU/Linux

$ fish --version
fish, version 2.4.0

$ omf describe bobthefish
Package: bobthefish
Description: A Powerline-style, Git-aware fish theme optimized for awesome.
Repository: https://github.com/oh-my-fish/theme-bobthefish
Maintainer:

$ omf version
Oh My Fish version 6
```

**Comment by bobthecow** [comment]
This is caused by the font rendering in your terminal app. Unfortunately fish and bobthefish have no control over that at all. You might be able to adjust font size or line height to get it to go away?
