### ISSUE TITLE
Git autocomplete freezes with fasd in fish 3 on OSX

### ISSUE THREAD

**Issue by domoritz** [oh-my-fish/theme-bobthefish#185]
See also https://github.com/oh-my-fish/plugin-cd/issues/11

I'm running on OSX with fish 3 and fisherman with the following two plugins.

```
oh-my-fish/theme-bobthefish
oh-my-fish/plugin-fasd
```

When I try to run autocomplete for a non-existing branch in git, my shell freezes.

```
git checkout dshfgkldfhgkl<TAB>
```

**Comment by skycaptain** [comment]
Having the same issue when setting a remote: `git remote add origin https://...`. As soon as I copy-paste an unknown url, the shell freezes. It works if the same command is already in the history. Uninstalling fasd work for me.

**Comment by domoritz** [comment]
Fish 3.0.1 might have a fix for this (https://github.com/fish-shell/fish-shell/issues/5541).

**Comment by bobthecow** [comment]
Yeah, I was going to make the same comment. I’m pretty confident this is the issue. Feel free to re-open if things don’t get better after 3.0.1.
