### ISSUE TITLE
superpowers (root) prompt section color does not blend in

### ISSUE THREAD

**Issue by diggit** [oh-my-fish/theme-bobthefish#192]
As title says, setting manually `color_initial_segment_su` works, but not as expected. Arrow following this section is not properly colored.

![19-03-04_15 51 24](https://user-images.githubusercontent.com/512025/53740842-678f3b00-3e95-11e9-8015-fb2644fdf6dd.png)

**Comment by bobthecow** [comment]
i'm afraid this isn't supported by bobthefish. the first three flags (exit, su and jobs) are intended to be in a single segment with a single background color, just like all the git flags are intended to be in a single segment with a single color.
