### ISSUE TITLE
Can't make the user's name disappear

### ISSUE THREAD

**Issue by InnovativeInventor** [oh-my-fish/theme-bobthefish#193]
![image](https://user-images.githubusercontent.com/20117409/54167708-69cb3980-4441-11e9-92c5-5cfa01961239.png)

These were also set in `Config.fish`. It appears that I can't get rid of `max`, which is vaguely annoying when there is too much text on one line. Awesome project, btw!

**Comment by bobthecow** [comment]
I don't think you're using bobthefish.

**Comment by InnovativeInventor** [comment]
Yeah, I'm using it in conjunction with [powerline-shell](https://github.com/b-ryan/powerline-shell).
