### ISSUE TITLE
[Feature request] Add togglable kube namespace to prompt

### ISSUE THREAD

**Issue by tlpbu** [oh-my-fish/theme-bobthefish#198]
Currently only current context is displayed in prompt when `theme_display_k8s_context' is set to `yes`.

Please consider adding:
- namespace value to prompt;
- add possibility to quickly toggle kube content:namespace globally and for session to see this only when working with Kubernetes cluster.

Functionally similar example containing above features for bash and zsh:
 https://github.com/jonmosco/kube-ps1

**Comment by bobthecow** [comment]
I don’t personally use kubernetes, so I don’t have strong opinions on how this should work. I’m happy to accept pull requests, though :)
