### ISSUE TITLE
Solarized scheme looks odd in CentOS

### ISSUE THREAD

**Issue by ffabulous** [oh-my-fish/theme-bobthefish#199]
`solarized-dark` color scheme looks as expected on macOS, but a bit brownish on CentOS. Do you have any ideas about it?

- macOS:
<img width="387" alt="스크린샷 2019-05-08 오후 5 24 19" src="https://user-images.githubusercontent.com/4755373/57361363-372a8c80-71b7-11e9-8b46-83017db77a54.png">

- CentOS:
<img width="368" alt="스크린샷 2019-05-08 오후 5 26 26" src="https://user-images.githubusercontent.com/4755373/57361361-372a8c80-71b7-11e9-9b52-e852f4af2b8f.png">

BTW, I'm a big fan of your theme. appreciate your work 👍

**Comment by bobthecow** [comment]
I don’t know, sorry. Did you set your terminal’s color scheme to solarized too?

**Comment by ffabulous** [comment]
Okay. I'll close this issue with a partial solution.

I also had this brownized issue when I used bobthefish with tmux in macOS.
Including the lines below to `~/.tmux.conf` solved the problem. (true color support)
```
set -g default-terminal 'xterm-256color'
set -ga terminal-overrides ',xterm-256color:Tc'
```

In CentOS, nothing works so far 😢

**Comment by krkhan** [comment]
@ffabulous that helped me too with the brownised issue, thanks!
