### ISSUE TITLE
Lost the nerd theme

### ISSUE THREAD

**Issue by pnunn** [oh-my-fish/theme-bobthefish#201]
I'm sure this is just because I'm new to fish and have no clue, but I did have bobthefish looking OK, but decided to run fish_config and change the prompt to something else.
Now I have NO clue how to get the bobthefish prompt back. I've tried a few different things but so far no joy.
How do you do that??
Ta
Peter.

**Comment by pioneerskies** [comment]
Would you mind to list :) I think it would be easier for all of us to help.

My first bet would be `omf theme bobthefish`, but it could seem too obvious :P and that is probably just a misunderstanding

**Comment by pnunn** [comment]
I assume you mean omf list (sorry, really new to fish)
 omf list
Plugins
bang-bang	fish-spec	omf

Themes
agnoster	batman		bobthefish	default

 omf theme bobthefish
[18:55:21] pnunn@pnunn-XPS-13-9370 /home/pnunn (0) 
>      

This is what I get.

**Comment by bobthecow** [comment]
OhI If you run fish_config and mess with the theme there, it writes a local fish_prompt function to your path and overwrites whatever you have specified in OMF.

Check `functions fish_prompt` to see where your prompt is defined. If it's not one you care about, delete it and restart fish.

**Comment by pnunn** [comment]
Thanks for the reply bobthecow. I tracked down the fish_prompt.fish function in .config/fish/functions and deleted it, but restarting has resulted in the prompt still being as shown. I can change to the agnoster theme and get the correct prompt, but omf theme bobthefish still returns to the odd prompt.

**Comment by pnunn** [comment]
OK, got it back.. had to remove bobthefish, install it, run fish doctor, follow the instructions and were back.. Now, how do I get files and dirs to be different colors in an ls for example? ls -lah is pretty, but ls is just all white.

**Comment by bobthecow** [comment]
`brew install lsd` 😛
