### ISSUE TITLE
Entering new line for typing new character in VSCode integrated terminal

### ISSUE THREAD

**Issue by xinbinhuang** [oh-my-fish/theme-bobthefish#203]
When the `previous command is invalid` symbol is active, every new character typing in the terminal will create a new line. How can I solve this?

![bug](https://user-images.githubusercontent.com/27927454/59142923-32095a80-897a-11e9-95d5-8e8059d18982.JPG)

**Comment by bobthecow** [comment]
i'm not sure. that's super weird. it seems like it might be a bug in vscode's terminal?

**Comment by bobthecow** [comment]
Closing due to lack of response.
