### ISSUE TITLE
an option to use $CMD_DURATION in right prompt instead of date

### ISSUE THREAD

**Issue by jrobeson** [oh-my-fish/theme-bobthefish#21]
I'm not sure if there are any performance implications or anything like that, but I've found it to be more useful than the time for my own purposes.

**Comment by bobthecow** [comment]
This do it for you?

<img width="762" alt="screen shot 2016-02-19 at 8 18 17 am" src="https://cloud.githubusercontent.com/assets/53660/13181322/601c86c6-d6e1-11e5-9a44-004d513d49b4.png">

**Comment by bobthecow** [comment]
I think it's a great idea to show that, and it seems to be free. In keeping with the principles behind bobthefish, I'd prefer to make it visible automatically any time it's > 0. Adding options is usually reserved for things that have performance implications.

**Comment by jrobeson** [comment]
I'd like to see the seconds if greater than 1000 ms, and minutes if greater than 60 seconds. like so https://github.com/davidcelis/dotfiles/blob/master/config/fish/functions/__fish_prompt_timing.fish unless it's not possible to do without too many calls.

**Comment by bobthecow** [comment]
Yeah, I like that.

Playing with it a bit, I feel like under 5s still works better as ms. Here's what I'm leaning towards:

<img width="762" alt="screen shot 2016-02-19 at 10 26 19 pm" src="https://cloud.githubusercontent.com/assets/53660/13194945/08ea5a3c-d758-11e5-9ae8-173486ae3d69.png">

As far as speed, on my machine doing this appears to slow things down by ~0.15ms each time the prompt is rendered, which seems totally reasonable :)

**Comment by bobthecow** [comment]
Okay, I pushed that version, and I think I'm pretty happy with it. I'll keep paying attention to it over the next week or two and see if everything still feels okay with real life usage. Let me know how you feel about it as well!

**Comment by jrobeson** [comment]
I'm trying it out, take any further lack of response as it working well!

Thanks!

**Comment by bobthecow** [comment]
:+1:

**Comment by jrobeson** [comment]
I just realized that `bc` might not actually be installed on every system

**Comment by bobthecow** [comment]
I tested on 2x Linux boxes and my Mac, and figured that was good enough. Know of an OS where it's not available by default?

**Comment by bobthecow** [comment]
Yeah, looks like RHEL / CentOS don't ship with it. I'll add an awk fallback, but the bc version is faster and cleaner so i'll keep that the default :)

**Comment by floam** [comment]
But you aren't really going to use fish on CentOS unless you let yum install bc for you. bc is a serious dependency of fish - the included `math` function is actually a bc wrapper and much of the included stuff in usr/share/fish/functions can't even work without it.

I'd seriously just use the math functions and if it returns an error code, disable that feature.

**Comment by jrobeson** [comment]
oh good call (i think)

**Comment by bobthecow** [comment]
Thanks @floam. I've updated to use `math` and gotten rid of the `awk` fallback.

:+1:

**Comment by bobthecow** [comment]
(and i'm not even bothering adding error handling until/unless someone complains :smile:)

**Comment by bobthecow** [comment]
@jrobeson I'm going to close this since it's shipped. Feel free to reopen (or open a new issue) if you have further feedback or requests :)
