### ISSUE TITLE
How to add arrow as on screenshot?

### ISSUE THREAD

**Issue by kimsanov** [oh-my-fish/theme-bobthefish#211]
In the theme screenshot there is a prefix arrow in prompt. But my installation of the theme doesn’t show this arrow. 
How should I enable it?

![AABC0511-7363-473C-9215-21A6E693D0C4](https://user-images.githubusercontent.com/29078534/63669988-2b092000-c7e4-11e9-91ec-72acadf1f10f.jpeg)

**Comment by bobthecow** [comment]
Oh! That arrow prefix is from iTerm. It's outside the shell :)

**Comment by kimsanov** [comment]
Got it! Thanks)
