### ISSUE TITLE
__bobthefish_prompt_status does not detect superuser on macOS

### ISSUE THREAD

**Issue by LucaFilipozzi** [oh-my-fish/theme-bobthefish#218]
On macOS, fish_prompt's superuser detection in __bobthefish_prompt_status fails because '/' is not writable.

Suggest changing `[ -w / ]` to `[ -w / -o (uname -s) = 'Darwin') ]` or `[ -w / -o -w /private/ ]`. This should not impact performance on non macOS machines due to logical short-circuit.

Let me know if you want a pull request.

**Comment by bobthecow** [comment]
good catch! let’s go with `[ -w / -o -w /private/ ]`. the directory checks are basically free, which is why we do them first before checking the user. we don’t have to worry about false positives, since we follow up with a check for the actual user id.

**Comment by bobthecow** [comment]
i’d love a pull request 😄

**Comment by LucaFilipozzi** [comment]
pull request #220 created
