### ISSUE TITLE
Weird segment terminator color

### ISSUE THREAD

**Issue by Crocmagnon** [oh-my-fish/theme-bobthefish#22]
Hello,
I just installed this awesome theme and I'm getting a problem with the "segment terminators" (the arrows at the end of each block in the prompt). They have a slightly different color than the segment.

Here is a screenshot : ![weird color](https://www.dropbox.com/s/mxanw7j8hyjlqtp/Capture%20d%27%C3%A9cran%202016-02-18%2000.06.28.png?raw=1)

You can see that the dark gray of the arrow is not the same as the previous one.

I'm using iTerm2 with Source Code Pro font but got the same result with any font.

By the way, what is the font you're using in the Readme screenshot ?

**Comment by bobthecow** [comment]
Unfortunately there's not much we can do about those colors. What you're seeing is a side effect of the way bobthefish (and every other powerline-like thing) works: the "background" of the segment is the background color, but on the segment dividers, the tip of the arrow is actually a triangle shaped glyph whose foreground color is the _last_ segment's background color, and whose background color matches the _next_ segment.

In iTerm 2 (and probably most or all other terminals?) when you change the opacity of the background, it changes the opacity not just of the main window, but of ever background color in the window. If you change your background to be _really_ transparent, it's a bit more obvious what's happening:

![bg-opacity-quirk](https://cloud.githubusercontent.com/assets/53660/13166725/b25bfe60-d67f-11e5-9935-2339dd3efbb7.gif)

That font is Source Code Pro (well, Sauce Code Pro, the Powerline patched version. Adobe doesn't let people call that one Source Code Pro :stuck_out_tongue:)

**Comment by Crocmagnon** [comment]
Thank you for your answer and explanation, it really helps !
I'm just gonna change my background transparency to none ;)

**Comment by bobthecow** [comment]
That's what I ended up doing :P

**Comment by ezintz** [comment]
![image](https://cloud.githubusercontent.com/assets/1742602/21222809/29a4ca66-c2c4-11e6-920f-90b04b371705.png)

In my iTerm2 version (Build 3.0.12) enabling the setting above fixes the issue.

**Comment by bobthecow** [comment]
Oh, nice. That's new. Thanks @ezintz!
