### ISSUE TITLE
Emojies break

### ISSUE THREAD

**Issue by jnnkB** [oh-my-fish/theme-bobthefish#223]
If I paste one emoji in terminal, the follwing happens: 
<img width="382" alt="image" src="https://user-images.githubusercontent.com/29376715/67971956-0b400f00-fc0e-11e9-8028-15a76957f55b.png">
It works in other omf themes:
<img width="133" alt="image" src="https://user-images.githubusercontent.com/29376715/67972429-f57f1980-fc0e-11e9-8983-603301c6ebfe.png">

**Comment by bobthecow** [comment]
This isn’t specific to bobthefish. Unfortunately this is fish and your terminal app disagreeing about how “wide” an emoji is. It will happen with any theme that uses a right prompt. 

You might be able to toggle a setting that will sort it out (in iterm, I believe it’s called “treat ambiguous characters as double width” or something similar). 

You can also disable the right prompt in bobthefish by adding an empty `fish_right_prompt` function somewhere in your fish config.

**Comment by jnnkB** [comment]
Thank you. This solved my problem
