### ISSUE TITLE
prompt: git projectdir shows the complete absolute path after git status

### ISSUE THREAD

**Issue by bretzel** [oh-my-fish/theme-bobthefish#229]
I have the absolute path on the left-side of GIT status, then the same absolute path on the right side of the git status  - so having twice the absolute path showed in the prompt.

**Comment by bretzel** [comment]
![bobthefish-issue](https://user-images.githubusercontent.com/1197610/70396617-b3e54980-19d8-11ea-950b-bc735830b50e.png)

**Comment by bretzel** [comment]
Please, notice the path in the image previous comment: 
it contains "++" characters somewhere in the line. So that's the "bug" that causes the prompt script to cancel the parsing of the path and then, takes the entirety of it.

If I have (free)time, I will take a look to the code and try to figure out how it is parsing the path and so on...

**Comment by bobthecow** [comment]
I believe this has been fixed now (by 46a89abb9918704ddce5489973e7d0caa865bd73)
