### ISSUE TITLE
break appearance of powerline

### ISSUE THREAD

**Issue by saymoncoppi** [oh-my-fish/theme-bobthefish#231]
Hey guys!
I'm facing this situation with the powerline:
![Captura de Tela_dde-desktop_20200108100352](https://user-images.githubusercontent.com/22059715/71985720-dfdb3100-3209-11ea-8330-31e9c3edf7a4.png)

How can I fix the appearance?

**Comment by bobthecow** [comment]
This is kind of the nature of the powerline fonts. They often work just fine without any additional tweaking, but unfortunately it can sometimes be difficult to get things all lined up just right. Experimenting with different fonts, sizes, weights, and different rendering settings in your terminal app might help.

**Comment by bobthecow** [comment]
Or, if you have share specific terminal and font combinations, maybe someone else has settings that work for them?
