### ISSUE TITLE
Ctrl+Right Issue

### ISSUE THREAD

**Issue by fastchain** [oh-my-fish/theme-bobthefish#232]
Hello,
at first thank you for bobthefish, it's superb! 

I have a little annoying issues and I don't know how to start to fix it.
Before bobthefish I used Ctrl+Right for word-by-word following in suggest, but after I've installed bobthefish, something weird is happening, when I use Ctrl+Right.

Where and how can change my Ctrl+Right behaviour back?

Thank you!

**Comment by bobthecow** [comment]
bobthefish doesn't do anything to ctrl+right behavior. Did you make any changes at the same time?

**Comment by fastchain** [comment]
@bobthecow  Hi! My fault, I completely  forgot that I switched to Terminator form xterm (because of the font issues), so it's Terminator's feature.

**Comment by bobthecow** [comment]
Ha! Glad you got it sorted :)
