### ISSUE TITLE
[Feature Request] An option to switch between one-line prompt and two-line prompt

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [oh-my-fish/theme-bobthefish#235]
It would be nice if bobthefish could have a two-line prompt interface like [nelsonjchen](https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md#nelsonjchen), especially useful when current path is very long.

![](https://cloud.githubusercontent.com/assets/5363/12106487/fe8b3c30-b314-11e5-9cbe-8b0e57dde741.png)

**Comment by bobthecow** [comment]
The option you're looking for is `set -g theme_newline_cursor yes` 🙂

**Comment by Aster-the-Med-Stu** [comment]
Oh thanks... I don't know there has already been an opinion.
