### ISSUE TITLE
some missing colors for Dracula colorscheme

### ISSUE THREAD

**Issue by Trollwut** [oh-my-fish/theme-bobthefish#242]
Hey folks!

Just wanted to say that there are missing colors for the Dracula colorscheme. Here is an example:

![](https://i.imgur.com/KoS3oAU.png)

As you see, `;` is colored correctly, also a single `&`. Erronous `;` and `&&` too.

But `&&` and `~` don't have Dracula colors, so I think this is missing.

Is there a fix for it or something currently planned?

**Comment by Trollwut** [comment]
linking @xsteadfastx as you might have a clue about that :)

**Comment by bobthecow** [comment]
colors in your input text are handled by fish itself, not the theme :)

**Comment by Trollwut** [comment]
that is true and I should have used my brain instead. thanks for clearing it up though :D

**Comment by bobthecow** [comment]
Heh. No worries :)
