### ISSUE TITLE
configure path segment delimiter

### ISSUE THREAD

**Issue by lestard** [oh-my-fish/theme-bobthefish#245]
Is it possible to change the path segment delimiter symbol (the slash)?
What I like to have is the look from the powerline-shell default that uses a `>` instead of the `/` as delimiter. See for example this screenshot from [https://github.com/b-ryan/powerline-shell](https://github.com/b-ryan/powerline-shell) (ignore the colors):

![screenshot](https://camo.githubusercontent.com/0a2840265b1613a607b32e068353aa5d1a2f1d0d/68747470733a2f2f7261772e6769746875622e636f6d2f622d7279616e2f706f7765726c696e652d7368656c6c2f6d61737465722f626173682d706f7765726c696e652d73637265656e73686f742e706e67)

**Comment by bobthecow** [comment]
No, it's not possible. It's also a bit at odds with bobthefish's preference for brevity and omitting visual distraction and less useful information. For your example above:

<img width="762" alt="Screen Shot 2020-05-02 at 9 06 15 AM" src="https://user-images.githubusercontent.com/53660/80869278-681b9100-8c54-11ea-8598-400a4695aa0e.png">
