### ISSUE TITLE
Miselading theme name displayed with custom theme colors

### ISSUE THREAD

**Issue by lightcap** [oh-my-fish/theme-bobthefish#247]
Creating a `bobthefish_colors` function to customize a theme works as expected with one exception: The output from `bobthefish_display_colors` shows the theme you set with `theme_color_scheme`. 

For example, in my `fish.config` I have `set theme_color_scheme dark`. But I've also created the custom `bobthefish_colors` function to override the dark theme.

The correct colors display for the tweaks I made (slight tweaks on the base16 color scheme) but the theme name isn't changed. I get why, but it's misleading and it'd be better to allow a custom name to be set — even if that's just `user` like it was.

<img width="457" alt="~ 2020-04-19 10-57-47" src="https://user-images.githubusercontent.com/12123/79695593-9d73b800-822c-11ea-8432-e91e87f29ee0.png">

**Comment by bobthecow** [comment]
Thanks for reporting!
