### ISSUE TITLE
`theme_git_worktree_support yes` breaks git features

### ISSUE THREAD

**Issue by diggit** [oh-my-fish/theme-bobthefish#249]
Hi, I've updated omf and all plugins after _very long time_ and git features stopped working. Prompt remains like there is no git repository even though there is. Behavior remains even after disabling my `bobthefish_colors` function.
After bisecting, commit introducing this problem is 5273c92fa56cc20338ab4a834ef07427acee07b7.
```
ArchLinux
Fish version: 3.1.0
Oh My Fish version 7-1-g4ff9981
```
Anybody else had/has similar problem?

**Comment by diggit** [comment]
I've isolated problem.
setting `theme_git_worktree_support yes` disables/breaks/mutes all git features even when they are explicitly enabled

**Comment by halimb** [comment]
@diggit same problem here, and thanks for the fix btw

**Comment by smourph** [comment]
Same here ! Thanks for the issue :)

From what I've seen, it may come from the `if [ "$theme_git_worktree_support" != 'yes' ]`clause in `__bobthefish_git_project_dir` function.
Maybe a missing `else` clause, or whatever else ? 👼

**Comment by simonkeng** [comment]
Same problem, setting `theme_git_worktree_support no` fixed it. Thanks
