### ISSUE TITLE
Different cursor shapes for modes in vi mode

### ISSUE THREAD

**Issue by 20manas** [oh-my-fish/theme-bobthefish#254]
There should be different cursor shapes for modes in vi mode to provide additional cues about the mode that is active. For example block for normal, line for insert.

I did not find any way to enable it in the theme and enabling the following (as mentioned in https://fishshell.com/docs/current/#vi-mode-commands) works temporarily but after switching from insert to normal mode the first time, it starts showing block for every mode:
```
set fish_cursor_default block
set fish_cursor_insert line
set fish_cursor_replace_one underscore
set fish_cursor_visual block
```
It'd be great to add support for this.

**Comment by bobthecow** [comment]
You should do this in `.config/fish/config.fish`. There's no need to add it to the theme :)

**Comment by 20manas** [comment]
That's where I added them. But as I said, initially, it shows the correct cursor shape, but once I switch to normal mode, then insert mode, it starts showing block shape for every mode.

**Comment by bobthecow** [comment]
That sounds like it might be a bug? I’d open an issue with the main fish repo. 

In any event, bobthefish doesn’t mess with cursors at all, so it’s not related to this theme.

**Comment by 20manas** [comment]
Alright, thanks for the help!
