### ISSUE TITLE
could not disable date

### ISSUE THREAD

**Issue by vzaliva** [oh-my-fish/theme-bobthefish#259]
I do not want date/time shown on the right side of the terminal after each command.
I've tried: `set -g theme_display_date no` but it did not help.
How can I disable the date display?

**Comment by vzaliva** [comment]
Any suggestions?

**Comment by bobthecow** [comment]
you can override `fish_right_prompt` (either to an empty function, to disable it completely, or to something more to your liking).

[see the "overrides" section of the README for more info](https://jira.corp.dropbox.com/browse/PAPER-3248?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D).

**Comment by vzaliva** [comment]
Adding: `function fish_right_prompt; end` to my `config.fish` solved the problem. Thanks
