### ISSUE TITLE
Option to disable the greeting?

### ISSUE THREAD

**Issue by SaswatPadhi** [oh-my-fish/theme-bobthefish#26]
I think it would be useful to have an option to disable the greeting. Or, set if only the user has not overridden the default greeting.

Thanks.

**Comment by derekstavis** [comment]
You can add the following line to your `$OMF_CONFIG/before.init.fish`

```
function fish_greeting; end
```

**Comment by bobthecow** [comment]
It _should_ only set if the user hasn't overridden the default greeting. If you're not seeing this behavior, there's a chance that OMF init process is messing it up right now, but once the new version of that lands, it shouldn't be an issue.

**Comment by SaswatPadhi** [comment]
Thanks.
I was using this plugin with Fisherman though, so not sure if it's a bug with OMF or Fisherman.

**Comment by bobthecow** [comment]
From what I understand of fisherman, it's either a bug or a design decision on that end. I'd recommend taking it up with them.

**Comment by bobthecow** [comment]
closing for now, since it seems to be a framework issue rather than a theme issue.
