### ISSUE TITLE
Disable header at startup

### ISSUE THREAD

**Issue by fedorpashin** [oh-my-fish/theme-bobthefish#260]
How can I disable this header?
<img width="634" alt="Снимок экрана 2020-07-20 в 22 11 13" src="https://user-images.githubusercontent.com/19939537/87976987-a6e41900-cad6-11ea-9540-bdb79028515b.png">

**Comment by bobthecow** [comment]
Override `fish_greeting` ([see the "overrides" section of the README for more info](https://github.com/oh-my-fish/theme-bobthefish/blob/e24516b39bb62183ab7d70a8395d78ebb58f081f/README.md#overrides)).
