### ISSUE TITLE
Add an indicator for Private mode

### ISSUE THREAD

**Issue by ayoisaiah** [oh-my-fish/theme-bobthefish#263]
If you start fish in private mode (`fish --private`), there's no way to know just by looking at the shell. I think it would be helpful to add such an indicator so it's easy to determine at a glance.

![image](https://user-images.githubusercontent.com/13372163/91441548-56e03b00-e868-11ea-9d94-6b240e5080ac.png)

**Comment by bobthecow** [comment]
Good call! I've added a lock icon when in private mode:

<img width="762" alt="Screen Shot 2020-08-28 at 7 00 39 AM" src="https://user-images.githubusercontent.com/53660/91575844-5f825100-e8fc-11ea-8c3e-4b4967dd31e1.png">
