### ISSUE TITLE
Where is the installation path for this theme?

### ISSUE THREAD

**Issue by netcan** [oh-my-fish/theme-bobthefish#27]
Where is the installation path for this theme?

**Comment by bobthecow** [comment]
If you're using OMF, running `omf install bobthefish` installs it in `~/.local/share/omf/themes/bobthefish`. If you're using another fish shell package manager, it'll be in a similar location, but it varies.

If you're not using a package manager, you should install OMF :)

Barring all that, creating a folder at `~/.config/fish/functions` and dropping all the `*.fish` files from this theme in there would work as well. But really, just install OMF.

**Comment by netcan** [comment]
Thank you for taking the time to respond.

**Comment by bobthecow** [comment]
No problem!
