### ISSUE TITLE
 system time zone is not used by the right prompt

### ISSUE THREAD

**Issue by champignoom** [oh-my-fish/theme-bobthefish#281]
The right prompt shows UTC+0 time by default, ignoring the system time zone.

**Comment by hundertzwoelf** [comment]
Hi, I had the same problem, but I fixed it by explicitly stating the timezone in my fish config.
In my case I added:
`set -g theme_date_timezone Europe/Berlin`

**Comment by Henriquelay** [comment]
Worked for me! Thanks

**Comment by bobthecow** [comment]
This is fixed now! Thanks for your patience.
