### ISSUE TITLE
Changing default colors of the commands and arguments

### ISSUE THREAD

**Issue by Diaoul** [oh-my-fish/theme-bobthefish#284]
First, thank you for the awesome theme, I really like it :heart: 

One thing I wish the theme could change is the color of the commands typed in the terminal. They are default fish color and clash with the theme.
See below a screenshot of the command `bobthefish_display_colors` printed in a shiny blue color. Same goes with command arguments in cyan or for the red color used when the command doesn't exist.

![image](https://user-images.githubusercontent.com/319220/100536805-536f9d80-3223-11eb-83f3-22fe40dfa881.png)

Is it possible for the theme to change that as well? Otherwise how could I do it manually if possible reusing the colors of the current fish theme?

**Comment by bobthecow** [comment]
Yes! There's an app called `fish_config` that launches a web UI for configuring the default colors. You can pick from pre-defined themes, or manually specify your own :)

**Comment by Diaoul** [comment]
Haha I feel silly now, did not remember there was a GUI for that... Thank you!
Gruvbox is not in there, I will create my own from its palette.
Maybe it is possible for the themes like bobthefish to add stuff here? Or customize it by default as it does with the prompt?

**Comment by Diaoul** [comment]
Here is what I came up with.

```fish
set orange   d65d0e
set brorange fe8019
set bg2      504945
set bg3      665c54
set bg4      7c6f64

set fish_color_autosuggestion     brblack
set fish_color_cancel             -r
set fish_color_command            cyan
set fish_color_comment            brblack
#set fish_color_cwd                cyan
#set fish_color_cwd_root           brred
set fish_color_end                $orange
set fish_color_error              red
set fish_color_escape             $orange
set fish_color_history_current    --bold
#set fish_color_host               normal
set fish_color_match              --background=brblue
set fish_color_normal             normal
set fish_color_operator           red
set fish_color_param              brwhite
set fish_color_quote              brgreen
set fish_color_redirection        bryellow
set fish_color_search_match       --background=$bg2
set fish_color_selection          -r
set fish_color_status             red
#set fish_color_user               brgreen
set fish_color_valid_path         --underline
set fish_pager_color_completion   normal
set fish_pager_color_description  yellow
set fish_pager_color_prefix       --bold --underline
set fish_pager_color_progress     brwhite --background=blue
```
