### ISSUE TITLE
Git work-tree support

### ISSUE THREAD

**Issue by KishanBagaria** [oh-my-fish/theme-bobthefish#29]
Can you add an option to not show the git work-tree and instead show the working directory exactly like other themes?

This is what I see:
<img width="611" alt="screen shot 2016-03-25 at 10 44 03 pm" src="https://cloud.githubusercontent.com/assets/1093313/14049464/777eb972-f2db-11e5-95ff-22a12b1e459a.png">

The working directory isn't shortened to ~/D/K/W/k which makes it eat a lot of width.

Also, what do you think about making it look like this for all users:

`~/D/K/W/k > master > _site`

This includes all three things and makes it more consistent because the working directory is the first thing like always, then the branch, and finally the relative work-tree.

Love the theme btw, it's amazing! :+1:

**Comment by bobthecow** [comment]
Hmm. It shouldn't look like that at all. 

Do you have symlinks or something else in a parent directory? Can you show me the value of $PWD and $HOME?

**Comment by bobthecow** [comment]
Oh. You're using a non-standard git dir or git work tree?

**Comment by KishanBagaria** [comment]
Non-standard git work tree.

```
$PWD  = /Users/kishan/Dropbox/Kishan/Websites/kishanbagaria
$HOME = /Users/kishan
```

**Comment by bobthecow** [comment]
For any given PWD, it should always be `~/A/b/c/ProjectName > master > path/from/project/root`. I don't use non-standard git dir or work tree, so I haven't run into this, but your screenshot is definitely wrong. I'll take a look :)

**Comment by KishanBagaria** [comment]
Repro:
```
mkdir -p git-bug/work
git-bug/
git init
echo "    worktree = ../work/" >> .git/config
trash ~/git-bug
```
<img width="822" alt="screen shot 2016-03-26 at 2 38 01 pm" src="https://cloud.githubusercontent.com/assets/1093313/14059205/68a6a8d0-f360-11e5-9ce0-58f10d7f44da.png">

What's your colour scheme btw?

**Comment by bobthecow** [comment]
To be honest, I'm not sure what would be the most useful output here. If possible, it should show the `> master >` segment at the worktree root, but it's entirely possible to be inside a git dir and not share any parent paths at all with the worktree.

What would you expect to see in these cases?

**Comment by KishanBagaria** [comment]
The full path in that case, but I think that's an unlikely scenario.

**Comment by bobthecow** [comment]
Or even something like:

```
git --git-dir ~/git/foo --work-tree ~/Projects/foo status
git --git-dir ~/git/bar --work-tree ~/Projects/bar status
```

… where there's a shared common parent (`~`), but it has nothing to do with the current project.

**Comment by bobthecow** [comment]
I feel like the best course of action is to put the `> master >` segment at the work tree root or the git dir root, whichever is the nearest parent.

So in your case, if you're inside `_site`, it'd be:

```
~/D/K/W/k/_site > master >
```

**Comment by KishanBagaria** [comment]
| `$PWD`               | `git-dir`             | `git-work-tree`      | Prompt                                   |
|----------------------|-----------------------|----------------------|------------------------------------------|
| `~/P/foo`            | `~/P/foo/.git`        | `~/P/foo/bar`        | `~/P/foo > master > bar`                 |
| `~/P/foo/bar`        | `~/P/foo/.git`        | `~/P/foo/bar`        | `~/P/foo/bar > master`                   |
| `~/P/foo`            | `~/git/foo/`          | `~/P/foo`            | Can you find git-dir automatically here? |

**Comment by bobthecow** [comment]
finding git-dir in [1] is only possible if GIT_DIR env variable is set.

**Comment by KishanBagaria** [comment]
Right, so you don't have to worry about the 3rd scenario, it's just gonna be the default prompt in that case.

**Comment by bobthecow** [comment]
unless they have GIT_DIR set, in which case it'll match the second scenario.

**Comment by bobthecow** [comment]
what about…

|        `$PWD`       |   `git-dir`    |   `git-work-tree`   |           Prompt           |
|---------------------|----------------|---------------------|----------------------------|
| `~/P/foo/bar/_site` | `~/P/foo/.git` | `~/P/foo/bar/_site` | `~/P/foo/b/_site > master` |

The general rule here would be:

 * truncated path to project directory (with project directory not truncated)
 * truncated path from project to work directory (with work directory not truncated)
 * branch name
 * full path from work directory to pwd

**Comment by KishanBagaria** [comment]
Well that case works fine now (after setting `GIT_DIR`):

![screen shot 2016-03-29 at 11 53 50 pm](https://cloud.githubusercontent.com/assets/1093313/14118960/8f6086e8-f609-11e5-98ce-256da2a6f0cc.png)

**Comment by bobthecow** [comment]
> Well that case works fine now (after setting GIT_DIR):

:+1:

**Comment by bobthecow** [comment]
i think i've settled on something i'm happy with:

<img width="762" alt="screen shot 2016-03-30 at 10 18 27 am" src="https://cloud.githubusercontent.com/assets/53660/14151024/ca3427a0-f660-11e5-84d2-6a46a6cb6b15.png">

the `> master >` segment always shows at the "project" directory level, and the workdir is highlighted the same way as the project directory.

**Comment by bobthecow** [comment]
@KishanBagaria it's messy right now, so i'll clean it up and push to a branch for you to test later today.

**Comment by bobthecow** [comment]
All the things:

<img width="946" alt="screen shot 2016-03-30 at 11 28 59 am" src="https://cloud.githubusercontent.com/assets/53660/14152969/9ff97aee-f66a-11e5-8f13-fc50cad214ac.png">

(Calling the parent folders `TestProjects` and `TestGit` prolly wasn't the best call, since you can't tell that the prompt actually "changed" on that last line, but underneath that truncation it says `~/TestGit/with-gitdir` :smile:

**Comment by KishanBagaria** [comment]
This is great! 😀  Sets it apart from other themes.

**Comment by KishanBagaria** [comment]
For `with-worktree`, I think it may make sense if you include the `worktree` after `> master >` in a muted color. Because I never cd into `_site` so I won't ever see the `_site`.

**Comment by bobthecow** [comment]
One more, with a deep worktree:

<img width="938" alt="screen shot 2016-03-30 at 12 25 46 pm" src="https://cloud.githubusercontent.com/assets/53660/14154673/9e9b0ffc-f672-11e5-9896-36006b87d8e0.png">

**Comment by bobthecow** [comment]
> For `with-worktree`, I think it may make sense if you include the `worktree` after `> master >` in a muted color. Because I never cd into `_site` so I won't ever see the `_site`.

By this, do you mean including it (muted) when you're in the parent directory, or just not bolding `_site` when you're in `_site`?

**Comment by KishanBagaria** [comment]
Never mind that, it's a bad idea. Your current approach seems :+1:

You're including only the contents of `$PWD` in the prompt, and bolding the `git-work-tree`.
So including anything that's not in `$PWD` will be confusing.

Maybe don't bold `with-worktree`/`with-deep-worktree` in the first segment so that people know `work-tree` is different?
Because if `$PWD` is `with-worktree` then there is no 3rd segment.

**Comment by bobthecow** [comment]
I've pushed the current work in progress to `git-workdir-support` branch. Try it out and let me know if you run into any issues!

**Comment by KishanBagaria** [comment]
Works good, thanks! :+1:

Appreciate you giving time into this Justin! :smile:

**Comment by bobthecow** [comment]
No problem :)

**Comment by bobthecow** [comment]
Hey! This has been merged into master, but hidden behind a flag. For most users, they'll never need this, so I figured we should save 'em the processing time. Enable it by setting `theme_git_worktree_support` to `yes` :)
