### ISSUE TITLE
It is possible make path after branch name follows 'fish_prompt_pwd_dir_length'

### ISSUE THREAD

**Issue by jesse23** [oh-my-fish/theme-bobthefish#294]
See snapshot, look at the path before and after branch name.

![image](https://user-images.githubusercontent.com/643912/105638371-44caee80-5e40-11eb-8b03-3977720a228b.png)

It is possible make path after branch name follows 'fish_prompt_pwd_dir_length'? Thanks...

**Comment by jesse23** [comment]
Never mind looks not doing that will be more consistent. :)

**Comment by bobthecow** [comment]
Yep, that was an intentional decision!

There's also an analogous `theme_project_dir_length` if you do want to truncate project directory paths.
