### ISSUE TITLE
Darwin message every time open terminal

### ISSUE THREAD

**Issue by bunlaikun** [oh-my-fish/theme-bobthefish#300]
When I use the default theme it not pops a message.

How can I remove it?

![1 1 1](https://user-images.githubusercontent.com/34414710/115327480-3bd88780-a1b9-11eb-84c4-c54eba05a14d.png)

> Darwin A-MacBook-Air.local 20.3.0 x86_64
 09:13:40  up  10:18,  3 users,  load average: 1.25, 1.53, 1.73

**Comment by bobthecow** [comment]
That's `fish_greeting`. See [the section on Overrides in the readme](https://github.com/oh-my-fish/theme-bobthefish#overrides) for instructions on overriding it with a message of your own (or nothing at all)

**Comment by bunlaikun** [comment]
got it, thanks
