### ISSUE TITLE
Is it possible to change user, "@" and hostname color?

### ISSUE THREAD

**Issue by ThoriumTextile** [oh-my-fish/theme-bobthefish#308]
AFAIK the closest solution [is this](https://github.com/oh-my-fish/theme-bobthefish/issues/284), but i tried using `set fish_color_host ` and `set fish_color_user ` to no avail.

Thanks in advance.

**Comment by bobthecow** [comment]
Yep, you can set a custom color scheme [via a `bobthefish_colors` function](https://github.com/oh-my-fish/theme-bobthefish/wiki/Custom-color-schemes), and set username and hostname colors there:

```fish
function bobthefish_colors -S -d 'Define a custom bobthefish color scheme'
  set -x color_username white black --bold
  set -x color_hostname white black
end
```
