### ISSUE TITLE
Strange colours in autocompletion prompt when used with "cd" command

### ISSUE THREAD

**Issue by enricobacis** [oh-my-fish/theme-bobthefish#31]
I just updated bobthefish, and I noticed a strange colour behaviour in the autocompletion prompt with the "cd" command. 

[![asciicast](https://asciinema.org/a/4531dvt2kokypyyo4xqpk4jj9.png)](https://asciinema.org/a/4531dvt2kokypyyo4xqpk4jj9)

Does it happen to you too?

**Comment by bobthecow** [comment]
Yes it does. Great catch!

Fixed in e01fe9a

**Comment by enricobacis** [comment]
I confirm it works now. Thanks!

**Comment by bobthecow** [comment]
Great, thank you :)
