### ISSUE TITLE
Hostname command not avaiable

### ISSUE THREAD

**Issue by Henriquelay** [oh-my-fish/theme-bobthefish#312]
https://github.com/oh-my-fish/theme-bobthefish/blob/626bd39b002535d69e56adba5b58a1060cfb6d7b/functions/fish_title.fish#L11

`hostname` commands are not avaiable on all machines, and not on mine running a Arch distro.
I fixed this on my machine by replacing `hostname` by `cat /etc/hostname`. Works just fine for me. Before the fix, it displays a error on every prompt.
I don't know if it's a good solution for the program since it depends on `cat`, a GNU program, and will make the program depend on that, just like it currently depends on `hostname`.

**Comment by bobthecow** [comment]
That's not guaranteed to exist, either 😬

<img width="762" alt="Screen Shot 2021-10-30 at 4 38 12 PM" src="https://user-images.githubusercontent.com/53660/139557719-49f49299-bf4f-4cf3-9ed9-0f2875514545.png">

`uname -n` is the portable POSIX way of doing it. Confirm that it works on your machine and I'll switch to that 🙂

**Comment by Henriquelay** [comment]
Works fine! Lets go with that :)

**Comment by bobthecow** [comment]
Should be fixed now!
