### ISSUE TITLE
No effect after install the bobthefish

### ISSUE THREAD

**Issue by woshichuanqilz** [oh-my-fish/theme-bobthefish#317]
After I run command `omf install bobthefish`, it shows the theme install successfully. But nothing changed on my terminal. 

I use alacritty, I install the power line font `Source Code Pro for Powerline`, and change the font setting in the alacritty config file. 

But still not take effect. 

My fish shell theme now is the basic theme. 

I try to reinstall the omf. But not work. So what should I do for the next for solve this issue? 

Thank you I advance. 

Here is the setting I write in the `fish.config`
```
# powerline theme settings
set -g theme_powerline_fonts yes
set -g theme_date_format "+%b-%d %H:%M"
set -g theme_display_date yes
set -g theme_date_timezone China/Shanghai
set -g theme_nerd_fonts yes
```

**Comment by bobthecow** [comment]
Run `functions fish_prompt`. I bet you have a higher-specificity function overriding it.

**Comment by frisodubach** [comment]
You might need to (re)move your fish prompt in .config/fish/functions/fish_prompt.fish
