### ISSUE TITLE
Other strange autocompletion issue

### ISSUE THREAD

**Issue by enricobacis** [oh-my-fish/theme-bobthefish#32]
I don't know how to describe this, when I enter `python -m` and then press <kbd>TAB</kbd>, I get an error.

[![asciicast](https://asciinema.org/a/009m8of7htcz6ms6273o0mu8l.png)](https://asciinema.org/a/009m8of7htcz6ms6273o0mu8l)

I think that the expected behaviour is not to propose the python modules, but at least not the `find` error.

**Comment by bobthecow** [comment]
This is almost certainly not related to the bobthefish theme. Try changing your theme to `default` and see if the problem persists?

**Comment by enricobacis** [comment]
You are right, it's the same for the default theme. It may be because I'm using fundle instead of oh-my-fish. I'll try to investigate a bit more. Thanks

**Comment by enricobacis** [comment]
Ok, the problem is related to this: http://superuser.com/questions/592057/find-command-is-giving-error-on-mountain-lion

**Comment by enricobacis** [comment]
And is already fixed on the fish-shell master branch, so it will be included in the next release.
