### ISSUE TITLE
The color background of the command prompt not shows out after install

### ISSUE THREAD

**Issue by woshichuanqilz** [oh-my-fish/theme-bobthefish#320]
system: Manjaro 21.2.0 Qonos
 WM: i3
 GTK Theme: Breeze [GTK2/3]
 Icon Theme: breeze

Install the bobfish by command `omf install bobthefish`

Change the theme by command `omf theme bobfish`

Powerline font installed. I use alacritty, 
In my alacritty config file: 
`family: Source Code Pro for Powerline`

After all this settings, the time at the right of the command line shows out, but the prompt on the left side seems no different as before, where am I wrong ?
![image](https://user-images.githubusercontent.com/11295355/147847865-7790c836-fc38-4e44-bd7e-a2340060f3db.png)

**Comment by bobthecow** [comment]
Notice that you _do_ have the correct right prompt, though.

You probably have a `fish_prompt` function defined with higher specificity than the one supplied by the theme. The most common reason for this is setting one via `fish_config`. Run `functions -D fish_prompt` to see where yours is defined:

<img width="448" alt="Screen Shot 2022-01-01 at 9 15 58 AM" src="https://user-images.githubusercontent.com/53660/147852579-91522a73-741e-4cb6-9997-0ea7700b25df.png">

If you see one that's not in `~/.local/share/omf/themes`, rename or delete the file and open a new shell.
