### ISSUE TITLE
How to show informative numbers in Git prompt?

### ISSUE THREAD

**Issue by Zesko** [oh-my-fish/theme-bobthefish#321]
Is that possible, this theme adds informative numbers of file change in Git Prompt?

For example: I want to like Git Prompt:
https://mariuszs.github.io/blog/2013/informative_git_prompt.html

**Comment by bobthecow** [comment]
```
set -g theme_display_git_ahead_verbose yes
set -g theme_display_git_dirty_verbose yes
set -g theme_display_git_stashed_verbose yes
```

**Comment by Zesko** [comment]
Thank the answer.
