### ISSUE TITLE
theme_display_node not showing node version...

### ISSUE THREAD

**Issue by chinesehemp** [oh-my-fish/theme-bobthefish#323]
I've updated the `config.fish` file with 

```
set -g theme_display_node yes
```
But I can't see the node version displayed in the prompt...

Is it supposed to show the node version in the prompt?

**Comment by evgeniy-vashchuk** [comment]
The same for me(

**Comment by chinesehemp** [comment]
This is no longer an issue for me. I can see the node version displayed as well as the icon

<img width="874" alt="Screenshot 2022-06-03 at 10 10 56" src="https://user-images.githubusercontent.com/58605231/171825276-7f6b648f-0e47-4f85-a489-d662c24e4db1.png">
 
How did I fix this? I switched over to Tide (https://github.com/IlanCosman/tide) instead of using OMF and bobthefish.
