### ISSUE TITLE
After install not show the powerline ? 

### ISSUE THREAD

**Issue by woshichuanqilz** [oh-my-fish/theme-bobthefish#332]
this is it look like after I install the theme follow the instructions
![image](https://user-images.githubusercontent.com/11295355/184405284-bb65455c-ea9e-4ed4-a147-c5efe4410803.png)

Seems I installed, but not show the powerline part.

here is the setting for this theme. 
The nerd font is installed 
```
# powerline theme settings
set -g theme_powerline_fonts yes
set -g theme_date_format "+%b-%d %H:%M"
set -g theme_display_date yes
set -g theme_date_timezone China/Shanghai
set -g theme_nerd_fonts yes
```

I use alacritty, font set in config file is like
```
  normal:
    family: Source Code Pro for Powerline

```

**Comment by Janosch** [comment]
I had the same problem. It looks like you have to install [powerline-shell](https://github.com/b-ryan/powerline-shell) yourself to make it work.

**Comment by woshichuanqilz** [comment]
> I had the same problem. It looks like you have to install [powerline-shell](https://github.com/b-ryan/powerline-shell) yourself to make it work.

Already solved check this. 

https://github.com/oh-my-fish/theme-bobthefish/issues/317
