### ISSUE TITLE
Right prompt is still underlined and using default terminal colors

### ISSUE THREAD

**Issue by s0r00t** [oh-my-fish/theme-bobthefish#35]
![Cleverly done M. Freeman, but you're not supposed to be here. As a matter of fact, you're not.](http://i.imgur.com/kthT7iM.png)

**Comment by bobthecow** [comment]
Do you have any idea where that underline started?

**Comment by s0r00t** [comment]
The autocompletion is also underlined.
What do you mean? I think this comes from the original prompt.

**Comment by bobthecow** [comment]
bobthefish doesn't use underline anywhere, so I'm not sure what would be causing this. Have you overridden any of the shell default colors to include underline?

**Comment by s0r00t** [comment]
I didn't change any colors myself, but when looking into fish_config, it wasn't using the default set...  
Seems like fisherman f*cked up. Setting back to default fixed it.
