### ISSUE TITLE
theme not working

### ISSUE THREAD

**Issue by donghao1393** [oh-my-fish/theme-bobthefish#353]
After successfully installed with `omf install bobthefish`, the color scheme of fish did not change at all.
Also, the following lines has been in `~/.config/fish/config.fish`, but new line not applied as well.
```fish
...
set -g theme_newline_cursor yes
set -g theme_newline_prompt '$ '
```

<img width="462" alt="image" src="https://github.com/oh-my-fish/theme-bobthefish/assets/138992704/0505d8a8-81f6-4fec-bbed-eb6f8b2d42be">

Would you let me know to activate bobthefish?

**Comment by bobthecow** [comment]
i'm not sure, to be honest. it's working as expected for me. is it possible your terminal app is messing with it? what terminal do you use?

**Comment by bobthecow** [comment]
oh, that doesn't look quite like bobthefish. have you used another powerline prompt in the past?

**Comment by donghao1393** [comment]
@bobthecow 

I am using iterm2. Theme not applied as well in Mac terminal.
It was some default color scheme from fish before.

**Comment by donghao1393** [comment]
It works after comment the following lines.
```bash
#function fish_prompt
#    eval ~/Documents/component_processes/container/powerline-go/powerline-go -error $status -jobs (count (jobs -p))
#end
```
But I was still wondering why powerline's command would affect the fish theme?

**Comment by bobthecow** [comment]
oh! bobthefish (and all fish themes) works by creating a `fish_prompt` function. you created one with higher specificity, so when fish went looking for the prompt it found yours!
