### ISSUE TITLE
Just display working tree, not sub folders

### ISSUE THREAD

**Issue by axlroden** [oh-my-fish/theme-bobthefish#358]
I seem to be missing a setting where I only show the directory I am in, is this possible ? I would like to avoid sub directories, unless im in a git repo or the like.

**Comment by bobthecow** [comment]
I'm not sure I understand. Can you give me an example of what you see, and what you'd prefer to see?

**Comment by axlroden** [comment]
What i see:
![image](https://github.com/oh-my-fish/theme-bobthefish/assets/4016762/c4a960ac-7a31-462f-ae7f-558c0bd8dbeb)

What I would love:
![image](https://github.com/oh-my-fish/theme-bobthefish/assets/4016762/eee14aa6-6492-4fb5-a748-ee6655a6bba5)

**Comment by bobthecow** [comment]
I just pushed a change that allows hiding the parent path. 

```
set -g theme_show_project_parent no
```

**Comment by axlroden** [comment]
Thankyou!!
