### ISSUE TITLE
Something wrong with naming

### ISSUE THREAD

**Issue by e-rakavest** [oh-my-fish/theme-bobthefish#368]
Why I see some date here(but I haven't this folder anywhere)?I've moved from Ubuntu 22.04(here everything works) to 24.04(doesn't work) Could you help please
![2024-06-27_13-09_1](https://github.com/oh-my-fish/theme-bobthefish/assets/31028332/2f98911b-3996-4ff6-9e53-b93d1f7660d1)
I found that is last git commit date but how I can disable it

**Comment by bobthecow** [comment]
That's a git tag name. If you use Nerd Fonts rather than Powerline it's a bit more clear :)

<img width="185" alt="Screenshot 2024-06-27 at 7 14 00 AM" src="https://github.com/oh-my-fish/theme-bobthefish/assets/53660/6f039d64-39ab-4e50-beb6-5471ce3c049d">

**Comment by e-rakavest** [comment]
Oh, sorry. I don't knew and was a little bit confused. Thanks a lot for very fast answer. I think that we can close that issue
