### ISSUE TITLE
hide python environment name and some timing status

### ISSUE THREAD

**Issue by donghao1393** [oh-my-fish/theme-bobthefish#369]
Hi, my fish shell is showing something in the right of the command line with python environment name and some timing status.
Can we hide them?

```bash
 dong.hao  ⎈ prod:   ³ base  ~/Documents
$ echo                                                                                                                                                                                                  (base) 609ms
```

**Comment by donghao1393** [comment]
I have figured out that the timing could be disabled.
```bash
set -g theme_display_cmd_duration no
```

But the python environment was still showing twice. Does anyone know how could we hide the second appearing?

**Comment by bobthecow** [comment]
if you're seeing python info twice, you're probably using virtual env (or something similar) that adds their own things to the prompt.

if it's virtual env, you can fix it by setting `set -x VIRTUAL_ENV_DISABLE_PROMPT 1`

you can also disable bobthefish's python info with `set -g theme_display_virtualenv no`

**Comment by donghao1393** [comment]
> if you're seeing python info twice, you're probably using virtual env (or something similar) that adds their own things to the prompt.
> 
> if it's virtual env, you can fix it by setting `set -x VIRTUAL_ENV_DISABLE_PROMPT 1`
> 
> you can also disable bobthefish's python info with `set -g theme_display_virtualenv no`

Hi, thank you for your response.
I am using miniconda. So I have enabled the display of env name in front of shell by `set -g theme_display_virtualenv yes`
` 2  donghao  ⎈ orbstack:   ³ base  ~/Downloads`
But, it was showing twice in a new line.
`$                                                                                                                                                                                                                                                                                                                                                                    (base)`
`set -x VIRTUAL_ENV_DISABLE_PROMPT 1` is not working

**Comment by donghao1393** [comment]
I successfully moved the display of conda environment name from right to left to avoid the long space by the following:
`set -g CONDA_LEFT_PROMPT yes`

**Comment by bobthecow** [comment]
right. bobthefish is adding the one in the left prompt. miniconda is adding the one to the right.

i don't actually use anaconda/miniconda, so i can't tell you how to remove the one on the right. `set -x VIRTUAL_ENV_DISABLE_PROMPT 1` is how you disable the virtualenv equivalent. There is _probably_ something like that for miniconda.
