### ISSUE TITLE
Option not to flag git stashes

### ISSUE THREAD

**Issue by caesar** [oh-my-fish/theme-bobthefish#37]
I have a lot of git stashes in some of my projects. Often I'll save half-finished work in a stash while working on something else.

It's really annoying to have bobthefish constantly show an orange git status line with the $ indicator. I'd like it to show as clean when there are no unchanged files in the current branch.

Would it be possible to add an option to disable this behaviour?

Happy to submit a pull request if you will accept a new option. :-)

**Comment by bobthecow** [comment]
Let's close this for now, because #43. We can re-address later if you feel that's not enough.

**Comment by caesar** [comment]
Thanks, I think #43 solves this for me.

On May 22 2016, at 8:27 pm, Justin Hileman &lt;notifications@github.com&gt;
wrote:  

> Closed [#37](https://github.com/oh-my-fish/theme-bobthefish/issues/37).

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/oh-my-
fish/theme-bobthefish/issues/37#event-668370232)![](https://github.com/notific
ations/beacon/ABfnNFw1ZivhsEyVb657PSCWEJceExegks5qEPR2gaJpZM4Ie8JY.gif)

**Comment by bobthecow** [comment]
Great!
