### ISSUE TITLE
Right prompt uses incorrect colour if $fish_color_autosuggestion is bold

### ISSUE THREAD

**Issue by caesar** [oh-my-fish/theme-bobthefish#39]
The colour of the right prompt is based on `$fish_color_autosuggestion`, which is great.
However, if `$fish_color_autosuggestion` has options such as bold, this fails and the default text colour is used. (This happens with colourschemes such as Solarized, where the bold colours are not in fact really bold.)

This is because you are doing `set_color $fish_color_autosuggestion[1]`.
If `$fish_color_autosuggestion` is, for example, "--bold green", this fails because `$fish_color_autosuggestion[1]` is just "--bold".

Instead, you should be using `set_color $fish_color_autosuggestion` (ie, without the `[1]`).

Is the `[1]` there for a reason? Removing it doesn't seem to break anything.

I will submit a pull request later.

(Sorry for three issues at once! :-) )

**Comment by bobthecow** [comment]
Nah, makes sense. I just never had a bold autosuggestion :)
