### ISSUE TITLE
Prompt shows wrong Python version in virtualenv

### ISSUE THREAD

**Issue by davidmehren** [oh-my-fish/theme-bobthefish#52]
Hi!

When I create a Python 3 virtualenv using `venv` or `virtualenv` and activate it, the prompt shows the wrong version 2.

I think this is because `__bobthefish_virtualenv_python_version` uses the name of the python executable to determine the version. This is (im my case at least) always `$venvdir/bin/python`, regardless of Python version and the prompt assumes Python 2.

Wouldn't it be possible to use the output of `python --version` instead?

**Comment by bobthecow** [comment]
Sorry for the delayed response.

I don't have a strong opinion here, as I don't usually use virtualenv. @rominf, any thoughts?

My one concern would be speed. If there's a significantly faster way to figure out what python version you're running, I'd prefer that. If it's about the same, we might as well be using `python --version`.

**Comment by rominf** [comment]
@bobthecow, I totally agree with @davidmehren.

See my PR. I don't see the difference between `cd`s into normal directories and directories with virtualenv.
