### ISSUE TITLE
Directory with @ breaks powerline prompt

### ISSUE THREAD

**Issue by MDykstra** [oh-my-fish/theme-bobthefish#54]
Matlab has the naming-convention `@Class` for a class-directory. Entering such
a directory, maintained under a Git-repository, breaks correct displaying of the
`theme-bobthefish` powerline shell prompt.

**Comment by MDykstra** [comment]
It doesn't break the prompt. The powerline just got longer than terminal width.

**Comment by bobthecow** [comment]
Good to hear :)
