### ISSUE TITLE
right direction arrow (i.e. end of prompt) green/red does not display correctly

### ISSUE THREAD

**Issue by miqui** [oh-my-fish/theme-bobthefish#6]
right direction arrow (i.e. end of prompt) green/red does not display correctly - i see a funny char
env: FC22 x64

installed powerline fonts.

**Comment by bobthecow** [comment]
Which powerline font version did you install? They changed the glyphs they use a while back, so older powerline fonts won't work.

**Comment by aadeshere1** [comment]
which one should we install ?
