### ISSUE TITLE
Add option to move cursor in a new line

### ISSUE THREAD

**Issue by diestrin** [oh-my-fish/theme-bobthefish#62]
Currently in my screen there's almost no space to type. I'd be awesome if I can move the cursor to a new line always.

![-v-h-p-1-w-wu 2016-09-03 13-30-02](https://cloud.githubusercontent.com/assets/909327/18227233/abe3f65e-71da-11e6-9e9d-7845314a475c.png)

**Comment by bobthecow** [comment]
Unfortunately I haven't found a way to do this which doesn't screw with the right prompt or make things really awkward when clearing the screen. I'm happy to accept pull requests if someone can figure it out :)

**Comment by nicbet** [comment]
Here is what works for me: 

I've added a simple echo after line 1326 
```
  # Insert newline
  echo -e ""

  # Start each line with a blank slate
  set -l __bobthefish_current_bg

  __bobthefish_maybe_display_colors
```

<img width="870" alt="screen shot 2017-03-28 at 7 50 25 pm" src="https://cloud.githubusercontent.com/assets/718340/24432388/e163e3c2-13ef-11e7-9c09-5ee708317a7f.png">

**Comment by bobthecow** [comment]
@nicbet Is this what @diestrin was looking for? I read it as wanting the prompt to stay on the line above, but the cursor to move down to the next line.

**Comment by diestrin** [comment]
Yeah, thanks @nicbet for the response, but that's not quite what I was looking for 👍

**Comment by druchoo** [comment]
@diestrin, @bobthecow, I took a try at this with #92. Let me know what you think.

**Comment by bobthecow** [comment]
This feature has been added with #92. Thanks @druchoo!
