### ISSUE TITLE
theme_display_vi and fish_vi_key_bindings

### ISSUE THREAD

**Issue by hastebrot** [oh-my-fish/theme-bobthefish#65]
When I use `theme_display_vi` in combination with `fish_vi_key_bindings` the prompt shows the vi mode prompt twich (one of `fish-shell` and one of `theme-bobthefish`).

I tested this in an Ubuntu guest session:

~~~
> fish --version
fish, version 2.3.1
> omf --version
Oh My Fish! 2
> omf install bobthefish
Installing theme bobthefish
✔ theme bobthefish successfully installed.
> fish_vi_key_bindings
> set -g theme_display_vi yes
~~~

**Update:** Here is a screenshot.

![fish-vi-mode](https://cloud.githubusercontent.com/assets/496255/18913097/3cd4eb50-8586-11e6-9816-1ed5bd4d550b.png)

**Comment by hastebrot** [comment]
Note that the VI mode functionality was changed in fish 2.3.0 (released May 21, 2016).

>The `fish_vi_mode` function is now deprecated in favour of `fish_vi_key_bindings`.

https://github.com/fish-shell/fish-shell/releases/tag/2.3.0

**Comment by hastebrot** [comment]
Quick work-around for `~/config/fish/config.fish`:

~~~
fish_vi_key_bindings
function fish_mode_prompt; end
~~~

**Comment by bobthecow** [comment]
Thanks for reporting. I've been meaning to fix this for a while :)
