### ISSUE TITLE
slow on fish 2.4.0

### ISSUE THREAD

**Issue by ycardon** [oh-my-fish/theme-bobthefish#66]
I'm running archlinux on rpi, omf/theme-bobthefish installed via fisherman.

Fish prompt became slow since 2.4.0 (I get a noticeable lag when I type).
I do not have this with the default prompt on fish 2.4.0 or bobthefish on 2.3.x

Does anyone have the same behaviour ?

**Comment by bobthecow** [comment]
I haven't run into this issue.

You get a noticeable lag when it renders each new prompt line, or while typing within the same line?

**Comment by ycardon** [comment]
both (nearly 1 second lag)

I dont have that issue either on my x86 machines, maybe it's unnoticeable on faster CPU.

**Comment by ycardon** [comment]
more testing : it's quite slow when I move the cursor on the same line, but the slowest is when fish gives me suggestions on typings and when the colour of what I type changes.

**Comment by bobthecow** [comment]
I don't have much insight here, but I do have a random idea: try disabling the right prompt.

**Comment by ycardon** [comment]
Well, disabling the right prompt seems to make it a little faster, but it's difficult to tell.

I'm going back to Fish 2.3.1 for the moment, maybe an other update somewhere will solve my problem.

Thanks for your answers anyway ^^

**Comment by bobthecow** [comment]
Alright. We'll close the issue for now. Feel free to reopen if/when you give 2.4.x another shot :)
