### ISSUE TITLE
error in __bobthefish_cmd_duration 

### ISSUE THREAD

**Issue by diggit** [oh-my-fish/theme-bobthefish#67]
Changes in $CMD_DURATION probably caused, that function `__bobthefish_cmd_duration` receives empty arguments when new shell is opened.

Error:
```
test returned eval errors:
h  Sun 18 Dec 2016 08:51:46 PM CET
	invalid integer ''
test returned eval errors:
	invalid integer ''
test returned eval errors:
	invalid integer ''
test returned eval errors:
	invalid integer ''
(standard_in) 1: syntax error
```

Simple solution is adding `[ "$CMD_DURATION" = '' ]; and return` before first $CMD_DURATION comparison to prevent comparison with 'nothing'. If empty, just return.

```
function __bobthefish_cmd_duration -S -d 'Show command duration'
  [ "$theme_display_cmd_duration" = "no" ]; and return
  [ "$CMD_DURATION" = '' ]; and return
  [ "$CMD_DURATION" -lt 100 ]; and return
...
...
```

**Comment by faho** [comment]
This was an issue in fish for about 6 weeks, right after we changed `test` to report errors for invalid integers and before https://github.com/fish-shell/fish-shell/commit/573916e5e29163f155d07dfd67372ab68686c98e.

@diggit: You'll want to upgrade fish. 2.5.0 is gonna have it, current git is good as well.

**Comment by bobthecow** [comment]
Thanks @faho!
