### ISSUE TITLE
Full paths in prompt.

### ISSUE THREAD

**Issue by ftpd** [oh-my-fish/theme-bobthefish#68]
It would be great to have option to see full directory names instead of shortened in prompt, so '~/.config/fish/functions' instead of ~/.c/f/functions'.
There is already an option to show abbreviated/not abbreviated path in window's title, so maybe you could add it for regular prompt also?

**Comment by mfernea** [comment]
I guess fish_prompt_pwd_dir_length variable should be used.

**Comment by ftpd** [comment]
It doesn't work - I've tried '0', '10', '1000' ane nothing has changed.

**Comment by bobthecow** [comment]
Thanks for the request! I've added support for the `$fish_prompt_pwd_dir_length` configuration variable. Set it to `0` to disable abbreviated paths, or any other number you fancy. Though I don't see much purpose for numbers besides `0` and `1` :)

I also added support for a `$theme_project_dir_length` setting to control abbreviation of the project-relative path segment.

**Comment by ftpd** [comment]
Great, everything works like a charm. Thank you @bobthecow for quick response.

**Comment by bobthecow** [comment]
No problem :)
