### ISSUE TITLE
set_color: Expected an argument

### ISSUE THREAD

**Issue by derekstavis** [oh-my-fish/theme-bobthefish#8]
Using bobthefish I'm getting an error every time the prompt is rendered:

![screen shot 2015-09-06 at 6 06 16 pm](https://cloud.githubusercontent.com/assets/1611639/9706638/065c3538-54c2-11e5-9759-bd57adfd88ea.png)

This error is different from fish 2.1.x `set_color`, which don't accept more than one parameter.

**Comment by bpinto** [comment]
It doesn't happen to me... have you tried on latest fish (2.2)?

**Comment by derekstavis** [comment]
Sorry for not answering. Yes. Updating to 2.2 solved the issue.

**Comment by bobthecow** [comment]
Sweet! :+1:
