### ISSUE TITLE
Dependencies not documented

### ISSUE THREAD

**Issue by tiberiuichim** [oh-my-fish/theme-bobthefish#80]
I've noticed, after an update form Debian Wheezy to Jessie, that bobthefish requires having `bc` installed. This isn't mentioned in the documentation.

**Comment by bobthecow** [comment]
bobthefish doesn't have a dependency on `bc`, it has a dependency on `math` (which in turn has a dependency on `bc`), and `math` has shipped with fish for _almost ten years_ :)

It sounds like the fish package on Debian needs to declare a dependency on `bc`?

**Comment by tiberiuichim** [comment]
Looks like a known issue. https://github.com/fish-shell/fish-shell/issues/2974

**Comment by bobthecow** [comment]
:+1:
