### ISSUE TITLE
"string" comand is failing, what should i install

### ISSUE THREAD

**Issue by sebassdc** [oh-my-fish/theme-bobthefish#81]
string: no order found
~/.config/fish/functions/fish_prompt.fish (line 1): string replace -r '^'"$current_dir"'($|/)' '' $PWD
                                                    ^
in command substitution
	called on line 149 of file ~/.config/fish/functions/fish_prompt.fish

in function '__bobthefish_project_pwd'
	called on line 464 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
	called on line 462 of file ~/.config/fish/functions/fish_prompt.fish

in function '__bobthefish_prompt_git'
	called on line 1345 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

**Comment by bobthecow** [comment]
what fish version are you running? what does `type string` say?

**Comment by RauliL** [comment]
I do not have `string` command installed at all. Is it some Mac OS X specific command?

**Comment by bobthecow** [comment]
`string` is a builtin that ships with Fish (as of about a year ago?) what Fish version do you have installed?

**Comment by RauliL** [comment]
2.3.1 from Ubuntu repository.

**Comment by sebassdc** [comment]
that was the problem. i fix it installing a newer build from source code

**Comment by bobthecow** [comment]
I might tag a legacy release from before I started using `string` and add it to the docs, so that people don't have to install a newer version from source just to use this theme.

**Comment by bobthecow** [comment]
^ if anyone comes across this issue and wants it, let me know. Otherwise, I won't do this because I'm lazy :)

**Comment by denisbrodbeck** [comment]
Well, I'd like to have this feature :smile:

Coming from oh-my-zsh and simply love the agnoster theme.

I'm currently on Ubuntu 16.04 and that ships with [fish v2.2.0](https://packages.ubuntu.com/xenial/fish) by default.

If the change's too time-consuming, no worry, I can survive until Ubuntu 18.04 gets released early next year, that comes with [fish v2.6.0](https://packages.ubuntu.com/bionic/fish).

**Comment by bobthecow** [comment]
Ok :) 

There's a branch now called `support/fish-2.2.x`. If you open `bobthefish` in your fish themes directory (probably `~/.local/share/omf/themes/bobthefish`) you should be able to check it out the support branch there, and it'll stay put even if you run `omf update`.

**Comment by bobthecow** [comment]
Let me know if you run into any trouble!

**Comment by denisbrodbeck** [comment]
@bobthecow Wow, thank you :+1: 

I someone wants to try this:
* `omf install bobthefish`
* switch to another shell like zsh or bash with `bash` (because you **will** get many errors with your commands while using the master branch)
* `cd ~/.local/share/omf/themes/bobthefish`
* `git checkout origin/support/fish-2.2.x`
* switch back to your new favorite shell with `fish`
