### ISSUE TITLE
Git integration broken since omf v5

### ISSUE THREAD

**Issue by kaatt** [oh-my-fish/theme-bobthefish#82]
Goes over two lines like:

```
~/D/Foo   master /Users/kaatt/Desktop/Foo
 ./o 
```

Works okay on non-git directories.

I've tried uninstalling and reinstalling omf and bobthefish.

**Comment by bobthecow** [comment]
Oh, that's no good. 

What's your fish version and OS?

**Comment by kaatt** [comment]
I just figured it's because I've got `set -g theme_git_worktree_support yes`

Unsetting that fixes it.

fish, version 2.5.0
macOS, version 10.12.3

**Comment by bobthecow** [comment]
Ahhh. Worktrees.

Do you actually use them, or had you just enabled that for fun?

**Comment by kaatt** [comment]
Yeah, don't actually use them. So it's all sorted out since I removed the line.

**Comment by bobthecow** [comment]
Thanks for reporting this. It's now fixed (but I wouldn't recommend enabling it unless you use it 😛)
