### ISSUE TITLE
Segment font colors "bleed" into surrounding

### ISSUE THREAD

**Issue by ph03** [oh-my-fish/theme-bobthefish#84]
Using the default dark color scheme I noticed that some segments font colors "bleed" into the surrounding segments (hard to explain, highlighted it for the output of `__bobthefish_display_colors`)

![segments](https://cloud.githubusercontent.com/assets/390527/23358229/6ca687d0-fce1-11e6-84da-387231cddc54.png)

For some segment boundaries this seems not to happen, so maybe it can be fixed for the listed ones as well? I'm particularly interested in the git ones :smile:

**Comment by bobthecow** [comment]
They "bleed" because the left side of the segment is using a background color, while the right side of the segment is using a triangle in the foreground color.

I'm not sure what font / OS / terminal combo you're using, but I see this in iTerm2 when "Use thin strokes for anti-aliased text" is enabled.

**Comment by ph03** [comment]
This is on Gnome Terminal 3.20.2 with DejaVu Sans Mono (nerd patches). I can also confirm that it's related to the anti-aliasing, since after changing the gnome setting from "RGBA" to "Grayscale" these artifacts are gone. As I see no other related regressions I'm ok to close this. Still, I'm wondering why these artifacts only show up for a subset of all segment colors (maybe it's a property of the anti-aliasing algorithm that manifests here).

**Comment by bobthecow** [comment]
I'm assuming RGBA anti-aliasing is subpixel anti-aliasing? If so, it's not surprising that it'd get different weirdness at the edges for different colors.
