### ISSUE TITLE
macOS and Fonts for git

### ISSUE THREAD

**Issue by rrosson** [oh-my-fish/theme-bobthefish#85]
No mater what I try I keep getting question mark glyphs when I am in a git repository. Please provide what i need to do to correct this. I use hombres and not macports.

TIA

**Comment by rrosson** [comment]
Figured it our. Sorry for the noise.

**Comment by bobthecow** [comment]
No worries! How could the docs have been better to make it easier to find in the first place?

**Comment by rrosson** [comment]
What got me was the font I was using in iTerm2. Probably a sample screenshot of the font you used in your demo file show your settings from Iterm2. Once I set that properly all looked like your video.   :)
--
Ron Rosson
ron@oneinsane.org <mailto:ron@oneinsane.org>
