### ISSUE TITLE
Add ability to customize glyphs

### ISSUE THREAD

**Issue by nemoDreamer** [oh-my-fish/theme-bobthefish#86]
It would be awesome if one could override the glyphs, similar to the `$theme_` options.

I don't know the correct "`fish`" for this, but something like "set locally from global or default":

`set -l __bobthefish_my_var (($theme_my_var) -o \u2191)` ?

or `if test ! -n $__bobthefish_my_var; set -l __bobthefish_my_var \u2191`, but that would allow for overriding w/ `''`...

**Comment by nemoDreamer** [comment]
Currently, they're being set w/ a forced local scope, which means you can't pre-define globally:

```fish
# Powerline glyphs
set -l __bobthefish_branch_glyph            \uE0A0
set -l __bobthefish_right_black_arrow_glyph \uE0B0
set -l __bobthefish_right_arrow_glyph       \uE0B1
set -l __bobthefish_left_black_arrow_glyph  \uE0B2
set -l __bobthefish_left_arrow_glyph        \uE0B3

# Additional glyphs
set -l __bobthefish_detached_glyph          \u27A6
set -l __bobthefish_tag_glyph               \u2302
set -l __bobthefish_nonzero_exit_glyph      '! '
set -l __bobthefish_superuser_glyph         '$ '
set -l __bobthefish_bg_job_glyph            '% '
set -l __bobthefish_hg_glyph                \u263F

# Python glyphs
set -l __bobthefish_superscript_glyph       \u00B9 \u00B2 \u00B3
set -l __bobthefish_virtualenv_glyph        \u25F0
set -l __bobthefish_pypy_glyph              \u1D56

# Ruby glyps
set -l __bobthefish_ruby_glyph              ''

# Vagrant glyphs
set -l __bobthefish_vagrant_running_glyph   \u2191 # ↑ 'running'
set -l __bobthefish_vagrant_poweroff_glyph  \u2193 # ↓ 'poweroff'
set -l __bobthefish_vagrant_aborted_glyph   \u2715 # ✕ 'aborted'
set -l __bobthefish_vagrant_saved_glyph     \u21E1 # ⇡ 'saved'
set -l __bobthefish_vagrant_stopping_glyph  \u21E3 # ⇣ 'stopping'
set -l __bobthefish_vagrant_unknown_glyph   '!'    # strange cases
```

**Comment by nemoDreamer** [comment]
I'm thinking also for the "git status" glyphs, which are currently ASCII, but would be great to be able to activate Powerline / Nerd font glyphs for...

**Comment by bobthecow** [comment]
What, specifically, do you want to change?

A bit about the philosophy of this theme: bobthefish is a flexible but opinionated theme. It's not really meant to be fully customizable; it has ideas about what are good options to support and what is just overkill. So in general, it errs on the side of offering configuration flags for toggling between multiple good ways of doing things, but not per-character customization.

If you've got a better set of glyphs in mind, let me know. If there are appropriate powerline or nerd font glyphs for things we're not using yet, let me know :)

**Comment by nemoDreamer** [comment]
I agree with the "opinionated" philosophy, but would like to propose #90 to make working-copy/fork overrides easier, just as they already are for Vagrant/etc.

**Comment by nemoDreamer** [comment]
I've added this to my "Use prettier Nerd Fonts glyphs" block -- to experiment, but I admit that they're not as subtle as the plain ASCII chars...:

```fish
    # set __bobthefish_git_dirty_glyph   \uF069 '' # nf-fa-asterisk
    # set __bobthefish_git_dirty_glyph   \uF41E '' # nf-oct-star
    set __bobthefish_git_dirty_glyph   \uF44F '' # nf-oct-code

    # set __bobthefish_git_staged_glyph  \uE729 '' # nf-dev-git_commit
    set __bobthefish_git_staged_glyph  \uF49B '' # nf-oct-watch

    # set __bobthefish_git_stashed_glyph \uF435 '' # nf-oct-pin
    set __bobthefish_git_stashed_glyph \uF0C6 '' # nf-fa-paperclip

    # set __bobthefish_git_untracked_glyph  \uF141 '' # nf-fa-ellipsis_h

    set __bobthefish_git_ahead_glyph   \uF47B # nf-oct-chevron_up
    set __bobthefish_git_behind_glyph  \uF47C # nf-oct-chevron_down
```

**Comment by bobthecow** [comment]
I like `nf-fa-paperclip` a lot for stashed.

`nf-oct-chevron_up` and `nf-oct-chevron_up` fit well with the theme, but I personally use +/- because i don't need the more verbose ahead/behind info, so i don't have strong opinions there :)

Most of the others do feel like they're a bit much.

For +/- I'm giving these a shot, and kind of like them so far:

```fish
    set __bobthefish_git_plus_glyph       \uF0DE '' # fa-sort-asc
    set __bobthefish_git_minus_glyph      \uF0DD '' # fa-sort-desc
    set __bobthefish_git_plus_minus_glyph \uF0DC '' # fa-sort
```

I especially like how the asc and desc glyphs line up with the carets for sort, so it feels like they're being toggled on/ off rather than having arrows move around.

Though if there were an `nf-oct-code` that went up/down rather than sideways, I'd probably go with that and the octicons chevrons for my +/- glyphs.

**Comment by nemoDreamer** [comment]
Love the `fa-sort` glyphs, nice find!
This is what I've been test-driving the past couple of days, and they play really well together:

```fish
set __bobthefish_git_dirty_glyph      \uF44F '' # nf-oct-code
set __bobthefish_git_staged_glyph     \uF417 '' # nf-oct-git_commit
set __bobthefish_git_stashed_glyph    \uF0C6 '' # nf-fa-paperclip
set __bobthefish_git_untracked_glyph  \uF128 '' # nf-fa-question
set __bobthefish_git_ahead_glyph      \uF47B # nf-oct-chevron_up
set __bobthefish_git_behind_glyph     \uF47C # nf-oct-chevron_down
set __bobthefish_git_plus_glyph       \uF0DE # fa-sort-asc
set __bobthefish_git_minus_glyph      \uF0DD # fa-sort-desc
set __bobthefish_git_plus_minus_glyph \uF0DC # fa-sort
```

<img width="252" alt="fish__teal_tin_weasel" src="https://cloud.githubusercontent.com/assets/9303/25821316/a0899508-3402-11e7-8d11-73593b0bf90a.png">

**Comment by nemoDreamer** [comment]
I do realize that adding these would come as a shock to folks who've grown to love the ASCII `...+-$`...!

**Comment by bobthecow** [comment]
We're already using `nf-oct-git_commit` for detached head, so it's prolly not the best for staged. i'm not sure i love `nf-oct-code` for modified files… i'll play with it for a bit to see if i come around.

**Comment by nemoDreamer** [comment]
🐶 of course...

Good ol' "diskette" to the rescue? As in _"Hey, you still need to save!"_

```fish
set __bobthefish_git_dirty_glyph      \uF448 '' # nf-oct-pencil 
set __bobthefish_git_staged_glyph     \uF0C7 '' # nf-fa-save 
```

<img width="413" alt="pencil_save" src="https://cloud.githubusercontent.com/assets/9303/25862735/245d34c0-34b7-11e7-90b6-8fd44f0b47b4.png">

**Comment by bobthecow** [comment]
>I do realize that adding these would come as a shock to folks who love the ASCII `...+-$`

I feel like anyone opting into nerd fonts is also opting into things like this. I have no problem ditching the ASCII here :)

**Comment by bobthecow** [comment]
I like `nf-oct-pencil` for dirty. I'll try `nf-fa-save` for staged for a bit. I'm liking the rest, with few exceptions :) 

I've always felt that "untracked" isn't a very interesting state. This is why untracked files don't change the color of the prompt segment, and they have the most subtle representation of all the git flags. Using `nf-fa-question` throws that balance off a bit, and makes it feel more … prominent (insistent?) than it needs to be.

**Comment by nemoDreamer** [comment]
Yup, I like the rationale for making it subtler, but if you're doing the kind of development where adding new files is rare, it's easy to "commit" and "push", and then have :doh: moment where you realize you didn't "add" that one file.
Git marks them w/ a `?` in "status", so I went w/ the nerd-icon equivalent. It's a shame that it's so bold, yes...

**Comment by bobthecow** [comment]
The nerd fonts glyph changes are merged, so I'm closing this for now. Thanks :)
