### ISSUE TITLE
allow multiple default usernames

### ISSUE THREAD

**Issue by donm** [oh-my-fish/theme-bobthefish#88]
Some people will have different usernames for their primary accounts on different machines, or multiple "primary" accounts on a single machine.  For example a username `bob` on personal computers, but `bfish` on company computers.  If fish config dotfiles are synced between accounts, hard-coding the `default_user` variable to a single value no longer works and you either need a per-machine config file for that variable, or to set the variable dynamically.

One option is to add a `default_users` variable that stores a list, with the same behavior as `default_user` as long as the current username is any of the strings of the list.  Optionally, it could take `user@host` strings so that the username `user` would only be a default user on the machine named `host`.  This is probably overkill, though.

I'm happy to implement it, this way or another way, but I wanted to run it by you first.    

(Background: If the current user id is equal to the value of the `default_user` variable, the username and host are not displayed in the prompt.)

**Comment by bobthecow** [comment]
I use local config and add `default_user` to my host-specific config files:

https://github.com/oh-my-fish/plugin-local-config

**Comment by donm** [comment]
Oh, sure, take the easy way out.  Recommend the perfect solution, which does what I *actually* want, and which you've already written.  

Thanks :)

**Comment by bobthecow** [comment]
Ha! No worries :)
