### ISSUE TITLE
If $RBENV_ROOT/version does not exist, subprocesses display error and keep running

### ISSUE THREAD

**Issue by cableray** [oh-my-fish/theme-bobthefish#89]
I started a fresh install and installed `bobthefish` and `rbenv`.  this caused the error:
```
<W> fish: An error occurred while redirecting file '~/.rbenv/version'
open: No such file or directory
```
rbenv had not created a `version` file.
also, I noticed when I tried `omf reload` that the child processes were still running:
```
Job	Group	State	Command
4	0	running	read -l global_ruby_version <$RBENV_ROOT/version
```

creating an empty `$RBENV_ROOT/version` file fixes the issue (but doesn't close the child processes that were already created), and deleting the file recreates the issue.

This may be an rbenv plugin issue, not a theme issue, but the theme is how I noticed the issue.

**Comment by bobthecow** [comment]
I don't have rbenv running on the machine I'm on, so I can't test IRL, but this should fix it. Do you mind confirming?

Open `~/.local/share/omf/themes/bobthefish/fish_prompt.fish` and replace line 681 with this:

```fish
    [ -e "$RBENV_ROOT/version" ]
      and read -l global_ruby_version <"$RBENV_ROOT/version"
```

If that works I'll update the theme :)

Thanks!

**Comment by cableray** [comment]
Looks good! No error messages when the file is missing. Thanks!

**Comment by bobthecow** [comment]
This has been fixed. Thanks again for reporting.
