### ISSUE TITLE
Wrong color for command

### ISSUE THREAD

**Issue by xurumelous** [oh-my-fish/theme-bobthefish#91]
I'm having trouble after I formatted my computer. For some reason, the command is white. I tried to find a fix but failed miserably. Is it a bug in the theme or at my side?

![white command](http://i.imgur.com/K096DJc.png)

**Comment by bobthecow** [comment]
By "the command" you mean `stree` and `git` in your screenshot? That's not controlled by the theme. But I believe white is the fish default for those.

**Comment by xurumelous** [comment]
Yes. I really believed it was. I'll take a look into fish configs then.

Thank you!

**Comment by bobthecow** [comment]
No problem!

**Comment by xurumelous** [comment]
For those who arrived here with the same issue, the solution that worked for me was:

```fish
set fish_color_command 005fd7 purple
```

Cheers!
