### ISSUE TITLE
Errors in fish_prompt.fish when changes directories

### ISSUE THREAD

**Issue by BBagTP** [oh-my-fish/theme-bobthefish#93]
When changing directories, the following error is printed:
```
No command 'string' found, did you mean:
 Command 'strings' from package 'binutils-multiarch' (main)
 Command 'strings' from package 'binutils' (main)
 Command 'spring' from package 'ruby-spring' (universe)
 Command 'spring' from package 'spring' (universe)
string: command not found
~/.config/fish/functions/fish_prompt.fish (line 1): string replace -r '^'"$real_home"'($|/)' '~$1' (dirname $current_dir)
                                                    ^
in command substitution
	called on line 73 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_pretty_parent”
	called on line 248 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
	called on line 246 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_path_segment”
	called on line 583 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_prompt_dir”
	called on line 1379 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
	called on standard input

in command substitution
	called on standard input

test: Missing argument at index 2
No command 'string' found, did you mean:
 Command 'spring' from package 'spring' (universe)
 Command 'spring' from package 'ruby-spring' (universe)
 Command 'strings' from package 'binutils-multiarch' (main)
 Command 'strings' from package 'binutils' (main)
string: command not found
~/.config/fish/functions/fish_prompt.fish (line 18):   string replace -ar '(\.?[^/]{'"$fish_prompt_pwd_dir_length"'})[^/]*/' '$1/' "$parent_dir/"
                                                       ^
in function “__bobthefish_pretty_parent”
	called on line 248 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
	called on line 246 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_path_segment”
	called on line 583 of file ~/.config/fish/functions/fish_prompt.fish

in function “__bobthefish_prompt_dir”
	called on line 1379 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
	called on standard input

in command substitution
	called on standard input
```

**Comment by girtsf** [comment]
You need to update to a newer fish version. (See  #81)

Perhaps the theme should check fish version and complain if the fish version is too old?

**Comment by BBagTP** [comment]
I've tried `omf update` and it says that OMF is up-to-date, despite it only being version 2.2.0. Any advice on getting a more recent (stable) version?

**Comment by bobthecow** [comment]
You need a newer version of `fish`, not of OMF. `string`is a builtin for the shell itself. You'd upgrade that through your system package manager.

**Comment by BBagTP** [comment]
Welp. By trying to install fish-2.6.0 without uninstalling the previous version of fish, I seem to have broken my shell. Opening any terminal (terminator, gnome-terminal, etc), I get the following:
```
You appear to be trying to launch an old fish binary with newer scripts
installed into /usr/share/fish

This is an unsupported configuration.

You may need to uninstall and reinstall fish!
```
I am seemingly unable to exit the fish shell and return to the gnome shell (any ideas on doing this?). 

Given that I can't use the terminal (and thus any `sudo` commands; to uninstall the app programmatically, or revert the config.fish file contents to that of fish-2.2.0), I can't figure out how to uninstall fish to start fresh.

**Comment by bobthecow** [comment]
Oh no! I haven't used terminator or gnome terminal in ages, but in iTerm (on OS X) you can open a new terminal window with an explicit shell. So whenever something like this happens I start a bash window and fix it from there :)

**Comment by BBagTP** [comment]
Crisis averted. 
I figured out a workaround by leveraging the "run a custom command instead of my shell" (in gnome-terminal) to run `sudo apt-get install - f` to fix the dependency, then I could change that option to run `sudo apt-get remove fish`. These all got executed upon restart of the terminal app. 

Finally, I installed the fish PPA to install fish-2.6.0.

**Comment by bobthecow** [comment]
Great! Glad we got that cleared up.
