### ISSUE TITLE
Ruby version 2.4.0 not printing in prompt

### ISSUE THREAD

**Issue by mrboot** [oh-my-fish/theme-bobthefish#94]
If I create a gemset with RVM in a directory using Ruby 2.3.0 or below:

`rvm use ruby-2.3.0@test --ruby-version --create`

and then enter that directory, bobthefish is correctly showing ` 2.3.0@test` in the prompt.

If I do the same with Ruby 2.4.0:

`rvm use ruby-2.4.0@test --ruby-version --create`

The prompt just lists the gemset: `@test`

I've looked through the script used to get the Ruby version and gemset but can't work out why this might be?

**Comment by bobthecow** [comment]
If I had to guess: bobthefish purposefully suppresses "default" info. It doesn't show your username unless you're being someone else. It doesn't show an icon for "nothing stashed in git" or "not dirty" or "not currently in a git repo". It just shows you things when they're different than the usual.

The full "ruby info" segment includes interpreter, version and gemset. But if your interpreter and version match the default, it'll just show the gemset. If your gemset is default (global) but your Ruby version isn't, it'll just show version. 

The relevant bits of code are here:

https://github.com/oh-my-fish/theme-bobthefish/blob/master/fish_prompt.fish#L658-L675

**Comment by mrboot** [comment]
Aarggh! You are so right and my apologies for opening an issue - should have been able to spot that.

**Comment by bobthecow** [comment]
No worries at all :)
