### ISSUE TITLE
Position of cursor is something wrong

### ISSUE THREAD

**Issue by re-fort** [oh-my-fish/theme-bobthefish#96]
In iTerm2, it looks like position of cursor is something wrong as shown below.
There is no problem in terminal though.
Is there any solution?

Before installing this theme:
<img width="416" alt="screen shot 0029-07-11 at 1 15 41 pm" src="https://user-images.githubusercontent.com/3705391/28050842-20d10c7c-663b-11e7-82b0-49becfe9edc1.png">
After installing this theme:
<img width="417" alt="screen shot 0029-07-11 at 12 58 08 pm" src="https://user-images.githubusercontent.com/3705391/28050443-c3f81e66-6638-11e7-8e22-79a772ab1ace.png">
iTerm2 version: 3.0.15
My setting in config.fish:
```
set -g theme_powerline_fonts no
set -g theme_nerd_fonts yes
```
In case that information is not enough, I'll provide.

**Comment by bobthecow** [comment]
If you don't set `theme_powerline_fonts` does it work properly?

**Comment by re-fort** [comment]
I tried, buit it does not work...

**Comment by bobthecow** [comment]
what is that `7` over on the left? is that the last character from 2017 on the right prompt?

**Comment by bobthecow** [comment]
ooh. it looks like there's too much space after your branch glyph. i bet it's the "ambiguous unicode character width" settings in iterm2.

<img width="577" alt="screen_shot_2017-07-12_at_4_50_28_am" src="https://user-images.githubusercontent.com/53660/28116443-f9a560a2-66bd-11e7-8867-0930fe20e6c7.png">

**Comment by re-fort** [comment]
This is it! It works!
Thanks for your help :)

**Comment by bobthecow** [comment]
Awesome!
