### ISSUE TITLE
Add NVM support

### ISSUE THREAD

**Issue by Yuri-M-Dias** [oh-my-fish/theme-bobthefish#97]
First of all, thanks for the amazing work on this theme!

Secondly, I'd like to request a Node Version Manager integration. I've noticed that there's only one theme that has this currently, and it'd be pretty helpful. 
I can add it myself over the next weekend if nobody wants to take it. I can add it like the ruby/python managers and make it optional with an env var.

**Comment by bobthecow** [comment]
Hi! Sorry I missed this one. Yes, NVM support would be great :)

**Comment by rcalabro** [comment]
+1
