### ISSUE TITLE
Cannot get fonts to work properly

### ISSUE THREAD

**Issue by CvBeijsterveldt** [oh-my-fish/theme-bobthefish#98]
Hi,
I've been trying to get this theme to work, and with it some various options to display the glyphs that come with it. However, whatever I do, it always ends up like this:

![image](https://user-images.githubusercontent.com/4046165/28880548-b918d5b6-77a5-11e7-8816-f57520e9170a.png)

I'm running an Arch Linux system with KDE Plasma and Konsole as my terminal.

Things I've done so far:
- Tried getting it to work with the Powerline fonts as described in the documentation (both with the install script from [https://github.com/powerline/fonts](https://github.com/powerline/fonts) and the instruction from [https://powerline.readthedocs.io/en/master/installation/linux.html#fonts-installation](https://powerline.readthedocs.io/en/master/installation/linux.html#fonts-installation)). Fonts are installed in my `.local/share/fonts` directory and `fc-list` lists them. Also, I can select them in Konsole.
- Made an attempt with Nerd Fonts, both with installations from the install script at [https://github.com/ryanoasis/nerd-fonts](https://github.com/ryanoasis/nerd-fonts) and the nerd-fonts-complete package from the AUR. I can select these fonts as well in Konsole (with the option 'Show all fonts' on) and I can see the text font change. All glyphs are still replaced with question marks though.
- Also tried out Awesome Terminal Fonts ([https://github.com/gabrielelana/awesome-terminal-fonts](https://github.com/gabrielelana/awesome-terminal-fonts)), installed through my package manager.
- Different settings in my config.fish, setting `theme_nerd_fonts yes` and setting `TERM` and `COLORTERM` to `screen-256color` and `xterm-256color`
- Tried restarting several times, moving fonts from my local folder to /usr/share/fonts and back, reïnstalling oh-my-fish and the theme, a different terminal, tried different fonts from the above collections (for DejaVu, Liberation and Hack mostly) etc, getting no step further in the process.

I'm hoping anyone here has a clue of what I'm doing wrong, as I cannot think of another option to try. Also, please let me know if you need any more information.

**Comment by bobthecow** [comment]
I haven't used Konsole in at least a decade, so I'm not sure I'll be much help. It does look like you're not actually using the patched font in Konsole, from your screenshot, so the settings there are where I'd spend time poking.

**Comment by CvBeijsterveldt** [comment]
Thank you for your reply, unfortunately I already tried that out. Here is a screenshot of my settings in Konsole:

![image](https://user-images.githubusercontent.com/4046165/28912427-84618054-7834-11e7-8498-8996afca324d.png)

I have also tried it with the Nerd fonts for Liberation and Hack. I can see the font being applied (text in Konsole changes) but it still can't seem to resolve any special symbols. I've also tried it on a different machine, freshly installed, with the same setup.

**Comment by CvBeijsterveldt** [comment]
Ok, got it figured out. Apparently, my en_NL.UTF-8 locale messed everything up. Setting it to en_US.UTF-8 made everything work as intended.
My apologies, this issue can be closed.

**Comment by bobthecow** [comment]
Glad you got it sorted! And thanks for the update. It'll give us one more thing to try the next time someone has issues :)

I would be interested to know why your locale had anything to do with characters from a reserved Unicode range.

**Comment by CvBeijsterveldt** [comment]
It might also have had something to do with the fact that I only had installed `en_US.UTF-8` with my locale.gen (I prefer to set my language to English on my computers), while having regional settings set to the Netherlands. This resulted in my locale becoming `en_NL.UTF-8`, which might (perhaps?) not contain the mapping for these characters.

Anyway, it was solved by installing `nl_NL.UTF-8` with locale-gen and manually setting my preferred language to English, while still keeping regional settings to be set to the Netherlands. So for future reference, check out your locale settings :P

**Comment by bobthecow** [comment]
Thanks!

**Comment by williamokano** [comment]
Sorry for "reviving" this post, but my LANG is en_US.UTF-8 and I still got question marks. Have installed the powerline and the fonts, still just question marks.
